conquistas = {
    "minecraft": "story/root",
    "stone age": "story/mine_stone",
    "getting an upgrade": "story/upgrade_tools",
    "acquire hardware": "story/smelt_iron",
    "suit up": "story/obtain_armor",
    "hot stuff": "story/lava_bucket",
    "isn't it iron pick": "story/iron_tools",
    "not today thank you": "story/deflect_arrow",
    "ice bucket challenge": "story/form_obsidian",
    "diamonds!": "story/mine_diamond",
    "we need to go deeper": "story/enter_the_nether",
    "cover me with diamonds": "story/shiny_gear",
    "enchanter": "story/enchant_item",
    "zombie doctor": "story/cure_zombie_villager",
    "eye spy": "story/follow_ender_eye",
    "the end?": "story/enter_the_end",
    "nether": "nether/root",
    "return to sender": "nether/return_to_sender",
    "those were the days": "nether/find_bastion",
    "hidden in the depths": "nether/obtain_ancient_debris",
    "subspace bubble": "nether/fast_travel",
    "a terrible fortress": "nether/find_fortress",
    "who is cutting onions?": "nether/obtain_crying_obsidian",
    "oh shiny": "nether/distract_piglin",
    "this boat has legs": "nether/ride_strider",
    "uneasy alliance": "nether/uneasy_alliance",
    "war pigs": "nether/loot_bastion",
    "country lode take me home": "nether/use_lodestone",
    "cover me in debris": "nether/netherite_armor",
    "spooky scary skeleton": "nether/get_wither_skull",
    "into fire": "nether/obtain_blaze_rod",
    'not quite "nine" lives': "nether/charge_respawn_anchor",
    "feels like home": "nether/ride_strider_in_overworld_lava",
    "hot tourist destinations": "nether/explore_nether",
    "withering heights": "nether/summon_wither",
    "local brewery": "nether/brew_potion",
    "bring home the beacon": "nether/create_beacon",
    "a furious cocktail": "nether/all_potions",
    "beaconator": "nether/create_full_beacon",
    "how did we get here?": "nether/all_effects",
    "the end": "end/root",
    "free the end": "end/kill_dragon",
    "the next generation": "end/dragon_egg",
    "remote getaway": "end/enter_end_gateway",
    "the end... again...": "end/respawn_dragon",
    "you need a mint": "end/dragon_breath",
    "the city at the end of the game": "end/find_end_city",
    "sky's the limit": "end/elytra",
    "great view from up here": "end/levitate",
    "adventure": "adventure/root",
    "voluntary exile": "adventure/voluntary_exile",
    "is it a bird?": "adventure/spyglass_at_parrot",
    "monster hunter": "adventure/kill_a_mob",
    "the power of books": "adventure/read_power_of_chiseled_bookshelf",
    "what a deal!": "adventure/trade",
    "crafting a new look": "adventure/trim_with_any_armor_pattern",
    "sticky situation": "adventure/honey_block_slide",
    "ol' betsy": "adventure/ol_betsy",
    "surge protector": "adventure/lightning_rod_with_villager_no_fire",
    "caves & cliffs": "adventure/fall_from_world_height",
    "respecting the remnants": "adventure/salvage_sherd",
    "sneak 100": "adventure/avoid_vibration",
    "sweet dreams": "adventure/sleep_in_bed",
    "hero of the village": "adventure/hero_of_the_village",
    "is it a balloon?": "adventure/spyglass_at_ghast",
    "a throwaway joke": "adventure/throw_trident",
    "it spreads": "adventure/kill_mob_near_sculk_catalyst",
    "take aim": "adventure/shoot_arrow",
    "monsters hunted": "adventure/kill_all_mobs",
    "postmortal": "adventure/totem_of_undying",
    "hired help": "adventure/summon_iron_golem",
    "star trader": "adventure/trade_at_world_height",
    "smithing with style": "adventure/trim_with_all_exclusive_armor_patterns",
    "two birds one arrow": "adventure/two_birds_one_arrow",
    "who's the pillager now?": "adventure/whos_the_pillager_now",
    "arbalistic": "adventure/arbalistic",
    "careful restoration": "adventure/craft_decorated_pot_using_only_sherds",
    "adventuring time": "adventure/adventuring_time",
    "sound of music": "adventure/play_jukebox_in_meadows",
    "light as a rabbit": "adventure/walk_on_powder_snow_with_leather_boots",
    "is it a plane?": "adventure/spyglass_at_dragon",
    "very very frightening": "adventure/very_very_frightening",
    "sniper duel": "adventure/sniper_duel",
    "bullseye": "adventure/bullseye",
    "husbandry": "husbandry/root",
    "bee our guest": "husbandry/safely_harvest_honey",
    "the parrots and the bats": "husbandry/breed_an_animal",
    "you've got a friend in me": "husbandry/allay_deliver_item_to_player",
    "whatever floats your goat!": "husbandry/ride_a_boat_with_a_goat",
    "best friends forever": "husbandry/tame_an_animal",
    "glow and behold!": "husbandry/make_a_sign_glow",
    "fishy business": "husbandry/fishy_business",
    "total beelocation": "husbandry/silk_touch_nest",
    "bukkit bukkit": "husbandry/tadpole_in_a_bucket",
    "smells interesting": "husbandry/obtain_sniffer_egg",
    "a seedy place": "husbandry/plant_seed",
    "wax on": "husbandry/wax_on",
    "two by two": "husbandry/bred_all_animals",
    "birthday song": "husbandry/allay_deliver_cake_to_note_block",
    "a complete catalogue": "husbandry/complete_catalogue",
    "tactical fishing": "husbandry/tactical_fishing",
    "when the squad hops into town": "husbandry/leash_all_frog_variants",
    "little sniffs": "husbandry/feed_snifflet",
    "a balanced diet": "husbandry/balanced_diet",
    "serious dedication": "husbandry/obtain_netherite_hoe",
    "wax off": "husbandry/wax_off",
    "the cutest predator": "husbandry/axolotl_in_a_bucket",
    "with our powers combined!": "husbandry/froglights",
    "planting the past": "husbandry/plant_any_sniffer_seed",
    "the healing power of friendship!": "husbandry/kill_axolotl_target",
}
