Encantamentos = {
    "aqua affinity": "aqua_affinity",
    "bane of arthropods": "bane_of_arthropods",
    "blast protection": "blast_protection",
    "channeling": "channeling",
    "curse of binding": "binding_curse",
    "curse of vanishing": "vanishing_curse",
    "depth strider": "depth_strider",
    "efficiency": "efficiency",
    "feather falling": "feather_falling",
    "fire aspect": "fire_aspect",
    "fire protection": "fire_protection",
    "flame": "flame",
    "fortune": "fortune",
    "frost walker": "frost_walker",
    "impaling": "impaling",
    "infinity": "infinity",
    "knockback": "knockback",
    "looting": "looting",
    "loyalty": "loyalty",
    "luck of the sea": "luck_of_the_sea",
    "lure": "lure",
    "mending": "mending",
    "multishot": "multishot",
    "piercing": "piercing",
    "power": "power",
    "projectile protection": "projectile_protection",
    "protection": "protection",
    "punch": "punch",
    "quick charge": "quick_charge",
    "respiration": "respiration",
    "riptide": "riptide",
    "sharpness": "sharpness",
    "silk touch": "silk_touch",
    "smite": "smite",
    "soul speed": "soul_speed",
    "sweeping edge": "sweeping",
    "swift sneak": "swift_sneak",
    "thorns": "thorns",
    "unbreaking": "unbreaking",
}
