Encantamentos = {
    "Aqua Affinity": "aqua_affinity",
    "Bane of Arthropods": "bane_of_arthropods",
    "Blast Protection": "blast_protection",
    "Channeling": "channeling",
    "Curse of Binding": "binding_curse",
    "Curse of Vanishing": "vanishing_curse",
    "Depth Strider": "depth_strider",
    "Efficiency": "efficiency",
    "Feather Falling": "feather_falling",
    "Fire Aspect": "fire_aspect",
    "Fire Protection": "fire_protection",
    "Flame": "flame",
    "Fortune": "fortune",
    "Frost Walker": "frost_walker",
    "Impaling": "impaling",
    "Infinity": "infinity",
    "Knockback": "knockback",
    "Looting": "looting",
    "Loyalty": "loyalty",
    "Luck of the Sea": "luck_of_the_sea",
    "Lure": "lure",
    "Mending": "mending",
    "Multishot": "multishot",
    "Piercing": "piercing",
    "Power": "power",
    "Projectile Protection": "projectile_protection",
    "Protection": "protection",
    "Punch": "punch",
    "Quick Charge": "quick_charge",
    "Respiration": "respiration",
    "Riptide": "riptide",
    "Sharpness": "sharpness",
    "Silk Touch": "silk_touch",
    "Smite": "smite",
    "Soul Speed": "soul_speed",
    "Sweeping Edge": "sweeping",
    "Swift Sneak": "swift_sneak",
    "Thorns": "thorns",
    "Unbreaking": "unbreaking",
}
