itens = {
    "Stone": "stone",
    "Granite": "granite",
    "Polished Granite": "polished_granite",
    "Diorite": "diorite",
    "Polished Diorite": "polished_diorite",
    "Andesite": "andesite",
    "Polished Andesite": "polished_andesite",
    "Grass Block": "grass_block",
    "Dirt": "dirt",
    "Coarse Dirt": "coarse_dirt",
    "Podzol": "podzol",
    "Cobblestone": "cobblestone",
    "Oak Planks": "oak_planks",
    "Spruce Planks": "spruce_planks",
    "Birch Planks": "birch_planks",
    "Jungle Planks": "jungle_planks",
    "Acacia Planks": "acacia_planks",
    "Dark Oak Planks": "dark_oak_planks",
    "Oak Sapling": "oak_sapling",
    "Spruce Sapling": "spruce_sapling",
    "Birch Sapling": "birch_sapling",
    "Jungle Sapling": "jungle_sapling",
    "Acacia Sapling": "acacia_sapling",
    "Dark Oak Sapling": "dark_oak_sapling",
    "Bedrock": "bedrock",
    "Sand": "sand",
    "Red Sand": "red_sand",
    "Gravel": "gravel",
    "Gold Ore": "gold_ore",
    "Iron Ore": "iron_ore",
    "Coal Ore": "coal_ore",
    "Oak Log": "oak_log",
    "Spruce Log": "spruce_log",
    "Birch Log": "birch_log",
    "Jungle Log": "jungle_log",
    "Acacia Log": "acacia_log",
    "Dark Oak Log": "dark_oak_log",
    "Stripped Oak Log": "stripped_oak_log",
    "Stripped Spruce Log": "stripped_spruce_log",
    "Stripped Birch Log": "stripped_birch_log",
    "Stripped Jungle Log": "stripped_jungle_log",
    "Stripped Acacia Log": "stripped_acacia_log",
    "Stripped Dark Oak Log": "stripped_dark_oak_log",
    "Stripped Oak Wood": "stripped_oak_wood",
    "Stripped Spruce Wood": "stripped_spruce_wood",
    "Stripped Birch Wood": "stripped_birch_wood",
    "Stripped Jungle Wood": "stripped_jungle_wood",
    "Stripped Acacia Wood": "stripped_acacia_wood",
    "Stripped Dark Oak Wood": "stripped_dark_oak_wood",
    "Oak Wood": "oak_wood",
    "Spruce Wood": "spruce_wood",
    "Birch Wood": "birch_wood",
    "Jungle Wood": "jungle_wood",
    "Acacia Wood": "acacia_wood",
    "Dark Oak Wood": "dark_oak_wood",
    "Oak Leaves": "oak_leaves",
    "Spruce Leaves": "spruce_leaves",
    "Birch Leaves": "birch_leaves",
    "Jungle Leaves": "jungle_leaves",
    "Acacia Leaves": "acacia_leaves",
    "Dark Oak Leaves": "dark_oak_leaves",
    "Sponge": "sponge",
    "Wet Sponge": "wet_sponge",
    "Glass": "glass",
    "Lapis Lazuli Ore": "lapis_ore",
    "Lapis Lazuli Block": "lapis_block",
    "Dispenser": "dispenser",
    "Sandstone": "sandstone",
    "Chiseled Sandstone": "chiseled_sandstone",
    "Cut Sandstone": "cut_sandstone",
    "Note Block": "note_block",
    "Powered Rail": "powered_rail",
    "Detector Rail": "detector_rail",
    "Sticky Piston": "sticky_piston",
    "Cobweb": "cobweb",
    "Grass": "grass",
    "Fern": "fern",
    "Dead Bush": "dead_bush",
    "Seagrass": "seagrass",
    "Sea Pickle": "sea_pickle",
    "Piston": "piston",
    "White Wool": "white_wool",
    "Orange Wool": "orange_wool",
    "Magenta Wool": "magenta_wool",
    "Light Blue Wool": "light_blue_wool",
    "Yellow Wool": "yellow_wool",
    "Lime Wool": "lime_wool",
    "Pink Wool": "pink_wool",
    "Gray Wool": "gray_wool",
    "Light Gray Wool": "light_gray_wool",
    "Cyan Wool": "cyan_wool",
    "Purple Wool": "purple_wool",
    "Blue Wool": "blue_wool",
    "Brown Wool": "brown_wool",
    "Green Wool": "green_wool",
    "Red Wool": "red_wool",
    "Black Wool": "black_wool",
    "Dandelion": "dandelion",
    "Poppy": "poppy",
    "Blue Orchid": "blue_orchid",
    "Allium": "allium",
    "Azure Bluet": "azure_bluet",
    "Red Tulip": "red_tulip",
    "Orange Tulip": "orange_tulip",
    "White Tulip": "white_tulip",
    "Pink Tulip": "pink_tulip",
    "Oxeye Daisy": "oxeye_daisy",
    "Brown Mushroom": "brown_mushroom",
    "Red Mushroom": "red_mushroom",
    "Block of Gold": "gold_block",
    "Block of Iron": "iron_block",
    "Oak Slab": "oak_slab",
    "Spruce Slab": "spruce_slab",
    "Birch Slab": "birch_slab",
    "Jungle Slab": "jungle_slab",
    "Acacia Slab": "acacia_slab",
    "Dark Oak Slab": "dark_oak_slab",
    "Stone Slab": "stone_slab",
    "Sandstone Slab": "sandstone_slab",
    "Petrified Oak Slab": "petrified_oak_slab",
    "Cobblestone Slab": "cobblestone_slab",
    "Brick Slab": "brick_slab",
    "Stone Brick Slab": "stone_brick_slab",
    "Nether Brick Slab": "nether_brick_slab",
    "Quartz Slab": "quartz_slab",
    "Red Sandstone Slab": "red_sandstone_slab",
    "Purpur Slab": "purpur_slab",
    "Prismarine Slab": "prismarine_slab",
    "Prismarine Brick Slab": "prismarine_brick_slab",
    "Dark Prismarine Slab": "dark_prismarine_slab",
    "Smooth Quartz": "smooth_quartz",
    "Smooth Red Sandstone": "smooth_red_sandstone",
    "Smooth Sandstone": "smooth_sandstone",
    "Smooth Stone": "smooth_stone",
    "Bricks": "bricks",
    "TNT": "tnt",
    "Bookshelf": "bookshelf",
    "Mossy Cobblestone": "mossy_cobblestone",
    "Obsidian": "obsidian",
    "Torch": "torch",
    "End Rod": "end_rod",
    "Chorus Plant": "chorus_plant",
    "Chorus Flower": "chorus_flower",
    "Purpur Block": "purpur_block",
    "Purpur Pillar": "purpur_pillar",
    "Purpur Stairs": "purpur_stairs",
    "Spawner": "spawner",
    "Oak Stairs": "oak_stairs",
    "Chest": "chest",
    "Diamond Ore": "diamond_ore",
    "Block of Diamond": "diamond_block",
    "Crafting Table": "crafting_table",
    "Farmland": "farmland",
    "Furnace": "furnace",
    "Ladder": "ladder",
    "Rail": "rail",
    "Cobblestone Stairs": "cobblestone_stairs",
    "Lever": "lever",
    "Stone Pressure Plate": "stone_pressure_plate",
    "Oak Pressure Plate": "oak_pressure_plate",
    "Spruce Pressure Plate": "spruce_pressure_plate",
    "Birch Pressure Plate": "birch_pressure_plate",
    "Jungle Pressure Plate": "jungle_pressure_plate",
    "Acacia Pressure Plate": "acacia_pressure_plate",
    "Dark Oak Pressure Plate": "dark_oak_pressure_plate",
    "Redstone Ore": "redstone_ore",
    "Redstone Torch": "redstone_torch",
    "Stone Button": "stone_button",
    "Snow": "snow",
    "Ice": "ice",
    "Snow Block": "snow_block",
    "Cactus": "cactus",
    "Clay": "clay_ball",
    "Jukebox": "jukebox",
    "Oak Fence": "oak_fence",
    "Spruce Fence": "spruce_fence",
    "Birch Fence": "birch_fence",
    "Jungle Fence": "jungle_fence",
    "Acacia Fence": "acacia_fence",
    "Dark Oak Fence": "dark_oak_fence",
    "Pumpkin": "pumpkin",
    "Carved Pumpkin": "carved_pumpkin",
    "Netherrack": "netherrack",
    "Soul Sand": "soul_sand",
    "Glowstone": "glowstone",
    "Jack o'Lantern": "jack_o_lantern",
    "Oak Trapdoor": "oak_trapdoor",
    "Spruce Trapdoor": "spruce_trapdoor",
    "Birch Trapdoor": "birch_trapdoor",
    "Jungle Trapdoor": "jungle_trapdoor",
    "Acacia Trapdoor": "acacia_trapdoor",
    "Dark Oak Trapdoor": "dark_oak_trapdoor",
    "Infested Stone": "infested_stone",
    "Infested Cobblestone": "infested_cobblestone",
    "Infested Stone Bricks": "infested_stone_bricks",
    "Infested Mossy Stone Bricks": "infested_mossy_stone_bricks",
    "Infested Cracked Stone Bricks": "infested_cracked_stone_bricks",
    "Infested Chiseled Stone Bricks": "infested_chiseled_stone_bricks",
    "Stone Bricks": "stone_bricks",
    "Mossy Stone Bricks": "mossy_stone_bricks",
    "Cracked Stone Bricks": "cracked_stone_bricks",
    "Chiseled Stone Bricks": "chiseled_stone_bricks",
    "Brown Mushroom Block": "brown_mushroom_block",
    "Red Mushroom Block": "red_mushroom_block",
    "Mushroom Stem": "mushroom_stem",
    "Iron Bars": "iron_bars",
    "Glass Pane": "glass_pane",
    "Melon": "melon",
    "Vines": "vine",
    "Oak Fence Gate": "oak_fence_gate",
    "Spruce Fence Gate": "spruce_fence_gate",
    "Birch Fence Gate": "birch_fence_gate",
    "Jungle Fence Gate": "jungle_fence_gate",
    "Acacia Fence Gate": "acacia_fence_gate",
    "Dark Oak Fence Gate": "dark_oak_fence_gate",
    "Brick Stairs": "brick_stairs",
    "Stone Brick Stairs": "stone_brick_stairs",
    "Mycelium": "mycelium",
    "Lily Pad": "lily_pad",
    "Nether Bricks": "nether_bricks",
    "Nether Brick Fence": "nether_brick_fence",
    "Nether Brick Stairs": "nether_brick_stairs",
    "Enchanting Table": "enchanting_table",
    "End Portal Frame": "end_portal_frame",
    "End Stone": "end_stone",
    "End Stone Bricks": "end_stone_bricks",
    "Dragon Egg": "dragon_egg",
    "Redstone Lamp": "redstone_lamp",
    "Sandstone Stairs": "sandstone_stairs",
    "Emerald Ore": "emerald_ore",
    "Ender Chest": "ender_chest",
    "Tripwire Hook": "tripwire_hook",
    "Block of Emerald": "emerald_block",
    "Spruce Stairs": "spruce_stairs",
    "Birch Stairs": "birch_stairs",
    "Jungle Stairs": "jungle_stairs",
    "Command Block": "command_block",
    "Beacon": "beacon",
    "Cobblestone Wall": "cobblestone_wall",
    "Mossy Cobblestone Wall": "mossy_cobblestone_wall",
    "Oak Button": "oak_button",
    "Spruce Button": "spruce_button",
    "Birch Button": "birch_button",
    "Jungle Button": "jungle_button",
    "Acacia Button": "acacia_button",
    "Dark Oak Button": "dark_oak_button",
    "Anvil": "anvil",
    "Chipped Anvil": "chipped_anvil",
    "Damaged Anvil": "damaged_anvil",
    "Trapped Chest": "trapped_chest",
    "Light Weighted Pressure Plate": "light_weighted_pressure_plate",
    "Heavy Weighted Pressure Plate": "heavy_weighted_pressure_plate",
    "Daylight Detector": "daylight_detector",
    "Block of Redstone": "redstone_block",
    "Nether Quartz Ore": "nether_quartz_ore",
    "Hopper": "hopper",
    "Chiseled Quartz Block": "chiseled_quartz_block",
    "Block of Quartz": "quartz_block",
    "Quartz Pillar": "quartz_pillar",
    "Quartz Stairs": "quartz_stairs",
    "Activator Rail": "activator_rail",
    "Dropper": "dropper",
    "White Terracotta": "white_terracotta",
    "Orange Terracotta": "orange_terracotta",
    "Magenta Terracotta": "magenta_terracotta",
    "Light Blue Terracotta": "light_blue_terracotta",
    "Yellow Terracotta": "yellow_terracotta",
    "Lime Terracotta": "lime_terracotta",
    "Pink Terracotta": "pink_terracotta",
    "Gray Terracotta": "gray_terracotta",
    "Light Gray Terracotta": "light_gray_terracotta",
    "Cyan Terracotta": "cyan_terracotta",
    "Purple Terracotta": "purple_terracotta",
    "Blue Terracotta": "blue_terracotta",
    "Brown Terracotta": "brown_terracotta",
    "Green Terracotta": "green_terracotta",
    "Red Terracotta": "red_terracotta",
    "Black Terracotta": "black_terracotta",
    "Barrier": "barrier",
    "Iron Trapdoor": "iron_trapdoor",
    "Hay Bale": "hay_block",
    "White Carpet": "white_carpet",
    "Orange Carpet": "orange_carpet",
    "Magenta Carpet": "magenta_carpet",
    "Light Blue Carpet": "light_blue_carpet",
    "Yellow Carpet": "yellow_carpet",
    "Lime Carpet": "lime_carpet",
    "Pink Carpet": "pink_carpet",
    "Gray Carpet": "gray_carpet",
    "Light Gray Carpet": "light_gray_carpet",
    "Cyan Carpet": "cyan_carpet",
    "Purple Carpet": "purple_carpet",
    "Blue Carpet": "blue_carpet",
    "Brown Carpet": "brown_carpet",
    "Green Carpet": "green_carpet",
    "Red Carpet": "red_carpet",
    "Black Carpet": "black_carpet",
    "Terracotta": "terracotta",
    "Block of Coal": "coal_block",
    "Packed Ice": "packed_ice",
    "Acacia Stairs": "acacia_stairs",
    "Dark Oak Stairs": "dark_oak_stairs",
    "Slime Block": "slime_block",
    "Grass Path": "grass_path",
    "Sunflower": "sunflower",
    "Lilac": "lilac",
    "Rose Bush": "rose_bush",
    "Peony": "peony",
    "Tall Grass": "tall_grass",
    "Large Fern": "large_fern",
    "White Stained Glass": "white_stained_glass",
    "Orange Stained Glass": "orange_stained_glass",
    "Magenta Stained Glass": "magenta_stained_glass",
    "Light Blue Stained Glass": "light_blue_stained_glass",
    "Yellow Stained Glass": "yellow_stained_glass",
    "Lime Stained Glass": "lime_stained_glass",
    "Pink Stained Glass": "pink_stained_glass",
    "Gray Stained Glass": "gray_stained_glass",
    "Light Gray Stained Glass": "light_gray_stained_glass",
    "Cyan Stained Glass": "cyan_stained_glass",
    "Purple Stained Glass": "purple_stained_glass",
    "Blue Stained Glass": "blue_stained_glass",
    "Brown Stained Glass": "brown_stained_glass",
    "Green Stained Glass": "green_stained_glass",
    "Red Stained Glass": "red_stained_glass",
    "Black Stained Glass": "black_stained_glass",
    "White Stained Glass Pane": "white_stained_glass_pane",
    "Orange Stained Glass Pane": "orange_stained_glass_pane",
    "Magenta Stained Glass Pane": "magenta_stained_glass_pane",
    "Light Blue Stained Glass Pane": "light_blue_stained_glass_pane",
    "Yellow Stained Glass Pane": "yellow_stained_glass_pane",
    "Lime Stained Glass Pane": "lime_stained_glass_pane",
    "Pink Stained Glass Pane": "pink_stained_glass_pane",
    "Gray Stained Glass Pane": "gray_stained_glass_pane",
    "Light Gray Stained Glass Pane": "light_gray_stained_glass_pane",
    "Cyan Stained Glass Pane": "cyan_stained_glass_pane",
    "Purple Stained Glass Pane": "purple_stained_glass_pane",
    "Blue Stained Glass Pane": "blue_stained_glass_pane",
    "Brown Stained Glass Pane": "brown_stained_glass_pane",
    "Green Stained Glass Pane": "green_stained_glass_pane",
    "Red Stained Glass Pane": "red_stained_glass_pane",
    "Black Stained Glass Pane": "black_stained_glass_pane",
    "Prismarine": "prismarine",
    "Prismarine Bricks": "prismarine_bricks",
    "Dark Prismarine": "dark_prismarine",
    "Prismarine Stairs": "prismarine_stairs",
    "Prismarine Brick Stairs": "prismarine_brick_stairs",
    "Dark Prismarine Stairs": "dark_prismarine_stairs",
    "Sea Lantern": "sea_lantern",
    "Red Sandstone": "red_sandstone",
    "Chiseled Red Sandstone": "chiseled_red_sandstone",
    "Cut Red Sandstone": "cut_red_sandstone",
    "Red Sandstone Stairs": "red_sandstone_stairs",
    "Repeating Command Block": "repeating_command_block",
    "Chain Command Block": "chain_command_block",
    "Magma Block": "magma_block",
    "Nether Wart Block": "nether_wart_block",
    "Red Nether Bricks": "red_nether_bricks",
    "Bone Block": "bone_block",
    "Structure Void": "structure_void",
    "Observer": "observer",
    "Shulker Box": "shulker_box",
    "White Shulker Box": "white_shulker_box",
    "Orange Shulker Box": "orange_shulker_box",
    "Magenta Shulker Box": "magenta_shulker_box",
    "Light Blue Shulker Box": "light_blue_shulker_box",
    "Yellow Shulker Box": "yellow_shulker_box",
    "Lime Shulker Box": "lime_shulker_box",
    "Pink Shulker Box": "pink_shulker_box",
    "Gray Shulker Box": "gray_shulker_box",
    "Light Gray Shulker Box": "light_gray_shulker_box",
    "Cyan Shulker Box": "cyan_shulker_box",
    "Purple Shulker Box": "purple_shulker_box",
    "Blue Shulker Box": "blue_shulker_box",
    "Brown Shulker Box": "brown_shulker_box",
    "Green Shulker Box": "green_shulker_box",
    "Red Shulker Box": "red_shulker_box",
    "Black Shulker Box": "black_shulker_box",
    "White Glazed Terracotta": "white_glazed_terracotta",
    "Orange Glazed Terracotta": "orange_glazed_terracotta",
    "Magenta Glazed Terracotta": "magenta_glazed_terracotta",
    "Light Blue Glazed Terracotta": "light_blue_glazed_terracotta",
    "Yellow Glazed Terracotta": "yellow_glazed_terracotta",
    "Lime Glazed Terracotta": "lime_glazed_terracotta",
    "Pink Glazed Terracotta": "pink_glazed_terracotta",
    "Gray Glazed Terracotta": "gray_glazed_terracotta",
    "Light Gray Glazed Terracotta": "light_gray_glazed_terracotta",
    "Cyan Glazed Terracotta": "cyan_glazed_terracotta",
    "Purple Glazed Terracotta": "purple_glazed_terracotta",
    "Blue Glazed Terracotta": "blue_glazed_terracotta",
    "Brown Glazed Terracotta": "brown_glazed_terracotta",
    "Green Glazed Terracotta": "green_glazed_terracotta",
    "Red Glazed Terracotta": "red_glazed_terracotta",
    "Black Glazed Terracotta": "black_glazed_terracotta",
    "White Concrete": "white_concrete",
    "Orange Concrete": "orange_concrete",
    "Magenta Concrete": "magenta_concrete",
    "Light Blue Concrete": "light_blue_concrete",
    "Yellow Concrete": "yellow_concrete",
    "Lime Concrete": "lime_concrete",
    "Pink Concrete": "pink_concrete",
    "Gray Concrete": "gray_concrete",
    "Light Gray Concrete": "light_gray_concrete",
    "Cyan Concrete": "cyan_concrete",
    "Purple Concrete": "purple_concrete",
    "Blue Concrete": "blue_concrete",
    "Brown Concrete": "brown_concrete",
    "Green Concrete": "green_concrete",
    "Red Concrete": "red_concrete",
    "Black Concrete": "black_concrete",
    "White Concrete Powder": "white_concrete_powder",
    "Orange Concrete Powder": "orange_concrete_powder",
    "Magenta Concrete Powder": "magenta_concrete_powder",
    "Light Blue Concrete Powder": "light_blue_concrete_powder",
    "Yellow Concrete Powder": "yellow_concrete_powder",
    "Lime Concrete Powder": "lime_concrete_powder",
    "Pink Concrete Powder": "pink_concrete_powder",
    "Gray Concrete Powder": "gray_concrete_powder",
    "Light Gray Concrete Powder": "light_gray_concrete_powder",
    "Cyan Concrete Powder": "cyan_concrete_powder",
    "Purple Concrete Powder": "purple_concrete_powder",
    "Blue Concrete Powder": "blue_concrete_powder",
    "Brown Concrete Powder": "brown_concrete_powder",
    "Green Concrete Powder": "green_concrete_powder",
    "Red Concrete Powder": "red_concrete_powder",
    "Black Concrete Powder": "black_concrete_powder",
    "Turtle Egg": "turtle_egg",
    "Dead Tube Coral Block": "dead_tube_coral_block",
    "Dead Brain Coral Block": "dead_brain_coral_block",
    "Dead Bubble Coral Block": "dead_bubble_coral_block",
    "Dead Fire Coral Block": "dead_fire_coral_block",
    "Dead Horn Coral Block": "dead_horn_coral_block",
    "Tube Coral Block": "tube_coral_block",
    "Brain Coral Block": "brain_coral_block",
    "Bubble Coral Block": "bubble_coral_block",
    "Fire Coral Block": "fire_coral_block",
    "Horn Coral Block": "horn_coral_block",
    "Tube Coral": "tube_coral",
    "Brain Coral": "brain_coral",
    "Bubble Coral": "bubble_coral",
    "Fire Coral": "fire_coral",
    "Horn Coral": "horn_coral",
    "Dead Brain Coral": "dead_brain_coral",
    "Dead Bubble Coral": "dead_bubble_coral",
    "Dead Fire Coral": "dead_fire_coral",
    "Dead Horn Coral": "dead_horn_coral",
    "Dead Tube Coral": "dead_tube_coral",
    "Tube Coral Fan": "tube_coral_fan",
    "Brain Coral Fan": "brain_coral_fan",
    "Bubble Coral Fan": "bubble_coral_fan",
    "Fire Coral Fan": "fire_coral_fan",
    "Horn Coral Fan": "horn_coral_fan",
    "Dead Tube Coral Fan": "dead_tube_coral_fan",
    "Dead Brain Coral Fan": "dead_brain_coral_fan",
    "Dead Bubble Coral Fan": "dead_bubble_coral_fan",
    "Dead Fire Coral Fan": "dead_fire_coral_fan",
    "Dead Horn Coral Fan": "dead_horn_coral_fan",
    "Blue Ice": "blue_ice",
    "Conduit": "conduit",
    "Iron Door": "iron_door",
    "Oak Door": "oak_door",
    "Spruce Door": "spruce_door",
    "Birch Door": "birch_door",
    "Jungle Door": "jungle_door",
    "Acacia Door": "acacia_door",
    "Dark Oak Door": "dark_oak_door",
    "Redstone Repeater": "repeater",
    "Redstone Comparator": "comparator",
    "Structure Block": "structure_block",
    "Turtle Shell": "turtle_helmet",
    "Scute": "scute",
    "Iron Shovel": "iron_shovel",
    "Iron Pickaxe": "iron_pickaxe",
    "Iron Axe": "iron_axe",
    "Flint and Steel": "flint_and_steel",
    "Apple": "apple",
    "Bow": "bow",
    "Arrow": "arrow",
    "Coal": "coal",
    "Charcoal": "charcoal",
    "Diamond": "diamond",
    "Iron Ingot": "iron_ingot",
    "Gold Ingot": "gold_ingot",
    "Iron Sword": "iron_sword",
    "Wooden Sword": "wooden_sword",
    "Wooden Shovel": "wooden_shovel",
    "Wooden Pickaxe": "wooden_pickaxe",
    "Wooden Axe": "wooden_axe",
    "Stone Sword": "stone_sword",
    "Stone Shovel": "stone_shovel",
    "Stone Pickaxe": "stone_pickaxe",
    "Stone Axe": "stone_axe",
    "Diamond Sword": "diamond_sword",
    "Diamond Shovel": "diamond_shovel",
    "Diamond Pickaxe": "diamond_pickaxe",
    "Diamond Axe": "diamond_axe",
    "Stick": "stick",
    "Bowl": "bowl",
    "Mushroom Stew": "mushroom_stew",
    "Golden Sword": "golden_sword",
    "Golden Shovel": "golden_shovel",
    "Golden Pickaxe": "golden_pickaxe",
    "Golden Axe": "golden_axe",
    "String": "string",
    "Feather": "feather",
    "Gunpowder": "gunpowder",
    "Wooden Hoe": "wooden_hoe",
    "Stone Hoe": "stone_hoe",
    "Iron Hoe": "iron_hoe",
    "Diamond Hoe": "diamond_hoe",
    "Golden Hoe": "golden_hoe",
    "Wheat Seeds": "wheat_seeds",
    "Wheat": "wheat",
    "Bread": "bread",
    "Leather Cap": "leather_helmet",
    "Leather Tunic": "leather_chestplate",
    "Leather Pants": "leather_leggings",
    "Leather Boots": "leather_boots",
    "Chainmail Helmet": "chainmail_helmet",
    "Chainmail Chestplate": "chainmail_chestplate",
    "Chainmail Leggings": "chainmail_leggings",
    "Chainmail Boots": "chainmail_boots",
    "Iron Helmet": "iron_helmet",
    "Iron Chestplate": "iron_chestplate",
    "Iron Leggings": "iron_leggings",
    "Iron Boots": "iron_boots",
    "Diamond Helmet": "diamond_helmet",
    "Diamond Chestplate": "diamond_chestplate",
    "Diamond Leggings": "diamond_leggings",
    "Diamond Boots": "diamond_boots",
    "Golden Helmet": "golden_helmet",
    "Golden Chestplate": "golden_chestplate",
    "Golden Leggings": "golden_leggings",
    "Golden Boots": "golden_boots",
    "Flint": "flint",
    "Raw Porkchop": "porkchop",
    "Cooked Porkchop": "cooked_porkchop",
    "Painting": "painting",
    "Golden Apple": "golden_apple",
    "Enchanted Golden Apple": "enchanted_golden_apple",
    "Sign": "sign",
    "Bucket": "bucket",
    "Water Bucket": "water_bucket",
    "Lava Bucket": "lava_bucket",
    "Minecart": "minecart",
    "Saddle": "saddle",
    "Redstone": "redstone",
    "Snowball": "snowball",
    "Oak Boat": "oak_boat",
    "Leather": "leather",
    "Milk Bucket": "milk_bucket",
    "Bucket of Pufferfish": "pufferfish_bucket",
    "Bucket of Salmon": "salmon_bucket",
    "Bucket of Cod": "cod_bucket",
    "Bucket of Tropical Fish": "tropical_fish_bucket",
    "Brick": "brick",
    "Sugar Cane": "sugar_cane",
    "Kelp": "kelp",
    "Dried Kelp Block": "dried_kelp_block",
    "Paper": "paper",
    "Book": "book",
    "Slimeball": "slime_ball",
    "Minecart with Chest": "chest_minecart",
    "Minecart with Furnace": "furnace_minecart",
    "Egg": "egg",
    "Compass": "compass",
    "Fishing Rod": "fishing_rod",
    "Clock": "clock",
    "Glowstone Dust": "glowstone_dust",
    "Raw Cod": "cod",
    "Raw Salmon": "salmon",
    "Tropical Fish": "tropical_fish",
    "Pufferfish": "pufferfish",
    "Cooked Cod": "cooked_cod",
    "Cooked Salmon": "cooked_salmon",
    "Ink Sac": "ink_sac",
    "Rose Red": "rose_red",
    "Cactus Green": "cactus_green",
    "Cocoa Beans": "cocoa_beans",
    "Lapis Lazuli": "lapis_lazuli",
    "Purple Dye": "purple_dye",
    "Cyan Dye": "cyan_dye",
    "Light Gray Dye": "light_gray_dye",
    "Gray Dye": "gray_dye",
    "Pink Dye": "pink_dye",
    "Lime Dye": "lime_dye",
    "Dandelion Yellow": "dandelion_yellow",
    "Light Blue Dye": "light_blue_dye",
    "Magenta Dye": "magenta_dye",
    "Orange Dye": "orange_dye",
    "Bone Meal": "bone_meal",
    "Bone": "bone",
    "Sugar": "sugar",
    "Cake": "cake",
    "White Bed": "white_bed",
    "Orange Bed": "orange_bed",
    "Magenta Bed": "magenta_bed",
    "Light Blue Bed": "light_blue_bed",
    "Yellow Bed": "yellow_bed",
    "Lime Bed": "lime_bed",
    "Pink Bed": "pink_bed",
    "Gray Bed": "gray_bed",
    "Light Gray Bed": "light_gray_bed",
    "Cyan Bed": "cyan_bed",
    "Purple Bed": "purple_bed",
    "Blue Bed": "blue_bed",
    "Brown Bed": "brown_bed",
    "Green Bed": "green_bed",
    "Red Bed": "red_bed",
    "Black Bed": "black_bed",
    "Cookie": "cookie",
    "Map": "filled_map",
    "Shears": "shears",
    "Melon Slice": "melon_slice",
    "Dried Kelp": "dried_kelp",
    "Pumpkin Seeds": "pumpkin_seeds",
    "Melon Seeds": "melon_seeds",
    "Raw Beef": "beef",
    "Steak": "cooked_beef",
    "Raw Chicken": "chicken",
    "Cooked Chicken": "cooked_chicken",
    "Rotten Flesh": "rotten_flesh",
    "Ender Pearl": "ender_pearl",
    "Blaze Rod": "blaze_rod",
    "Ghast Tear": "ghast_tear",
    "Gold Nugget": "gold_nugget",
    "Nether Wart": "nether_wart",
    "Potion": "potion",
    "Splash Potion": "splash_potion",
    "Lingering Potion": "lingering_potion",
    "Water Bottle": "potion{Potion:water}",
    "Uncraftable Potion": "potion{Potion:empty}",
    "Awkward Potion": "potion{Potion:awkward}",
    "Thick Potion": "potion{Potion:thick}",
    "Mundane Potion": "potion{Potion:mundane}",
    "Regeneration Potion (0:45)": "potion{Potion:regeneration}",
    "Swiftness Potion (3:00)": "potion{Potion:swiftness}",
    "Fire Resistance Potion (3:00)": "potion{Potion:fire_resistance}",
    "Poison Potion (0:45)": "potion{Potion:poison}",
    "Healing Potion": "potion{Potion:healing}",
    "Night Vision Potion (3:00)": "potion{Potion:night_vision}",
    "Weakness Potion (1:30)": "potion{Potion:weakness}",
    "Strength Potion (3:00)": "potion{Potion:strength}",
    "Slowness Potion (1:30)": "potion{Potion:slowness}",
    "Harming Potion": "potion{Potion:harming}",
    "Water Breathing Potion (3:00)": "potion{Potion:water_breathing}",
    "Invisibility Potion (3:00)": "potion{Potion:invisibility}",
    "Regeneration Potion II (0:22)": "potion{Potion:strong_regeneration}",
    "Swiftness Potion II (1:30)": "potion{Potion:strong_swiftness}",
    "Poison Potion II (0:22)": "potion{Potion:strong_poison}",
    "Healing Potion II": "potion{Potion:strong_healing}",
    "Strength Potion II (1:30)": "potion{Potion:strong_strength}",
    "Leaping Potion II (1:30)": "potion{Potion:strong_leaping}",
    "Harming Potion II": "potion{Potion:strong_harming}",
    "Regeneration Potion (2:00)": "potion{Potion:long_regeneration}",
    "Swiftness Potion (8:00)": "potion{Potion:long_swiftness}",
    "Fire Resistance Potion (8:00)": "potion{Potion:long_fire_resistance}",
    "Poison Potion (2:00)": "potion{Potion:long_poison}",
    "Night Vision Potion (8:00)": "potion{Potion:long_night_vision}",
    "Weakness Potion (4:00)": "potion{Potion:long_weakness}",
    "Strength Potion (8:00)": "potion{Potion:long_strength}",
    "Slowness Potion (4:00)": "potion{Potion:long_slowness}",
    "Leaping Potion (3:00)": "potion{Potion:leaping}",
    "Water Breathing Potion (8:00)": "potion{Potion:long_water_breathing}",
    "Invisibility Potion (8:00)": "potion{Potion:long_invisibility}",
    "Regeneration Potion II (1:00)": "potion{Potion:strong_regeneration}",
    "Swiftness Potion II (4:00)": "potion{Potion:strong_swiftness}",
    "Poison Potion II (1:00)": "potion{Potion:strong_poison}",
    "Strength Potion II (4:00)": "potion{Potion:strong_strength}",
    "Potion of the Turtle Master (0:20)": "potion{Potion:turtle_master}",
    "Potion of the Turtle Master (0:40)": "potion{Potion:long_turtle_master}",
    "Potion of the Turtle Master II (0:20)": "potion{Potion:strong_turtle_master}",
    "Potion of Slow Falling (1:30)": "potion{Potion:slow_falling}",
    "Potion of Slow Falling (4:00)": "potion{Potion:long_slow_falling}",
    "Regeneration Splash (0:33) Potion": "splash_potion{Potion:regeneration}",
    "Swiftness Splash (2:15) Potion": "splash_potion{Potion:swiftness}",
    "Fire Resistance Splash (2:15) Potion": "splash_potion{Potion:fire_resistance}",
    "Poison Splash (0:33) Potion": "splash_potion{Potion:poison}",
    "Healing Splash Potion": "splash_potion{Potion:healing}",
    "Night Vision Splash (2:15) Potion": "splash_potion{Potion:night_vision}",
    "Weakness Splash (1:07) Potion": "splash_potion{Potion:weakness}",
    "Strength Splash (2:15) Potion": "splash_potion{Potion:strength}",
    "Slowness Splash (1:07) Potion": "splash_potion{Potion:slowness}",
    "Harming Splash Potion": "splash_potion{Potion:harming}",
    "Water Breathing Splash (2:15) Potion": "splash_potion{Potion:water_breathing}",
    "Invisibility Splash (2:15) Potion": "splash_potion{Potion:invisibility}",
    "Regeneration II Splash (0:16) Potion": "splash_potion{Potion:strong_regeneration}",
    "Swiftness II Splash (1:07) Potion": "splash_potion{Potion:strong_swiftness}",
    "Poison II Splash (0:16) Potion": "splash_potion{Potion:strong_poison}",
    "Healing II Splash Potion": "splash_potion{Potion:strong_healing}",
    "Strength II Splash (1:07) Potion": "splash_potion{Potion:strong_poison}",
    "Leaping II Splash (1:07) Potion": "splash_potion{Potion:strong_leaping}",
    "Harming II Splash Potion": "splash_potion{Potion:strong_harming}",
    "Regeneration Splash (1:30) Potion": "splash_potion{Potion:long_regeneration}",
    "Swiftness Splash (6:00) Potion": "splash_potion{Potion:long_swiftness}",
    "Fire Resistance Splash (6:00) Potion": "splash_potion{Potion:long_fire_resistance}",
    "Poison Splash (1:30) Potion": "splash_potion{Potion:long_poison}",
    "Night Vision Splash (6:00) Potion": "splash_potion{Potion:long_night_vision}",
    "Weakness Splash (3:00) Potion": "splash_potion{Potion:long_weakness}",
    "Strength Splash (6:00) Potion": "splash_potion{Potion:long_strength}",
    "Slowness Splash (3:00) Potion": "splash_potion{Potion:long_slowness}",
    "Leaping Splash (2:15) Potion": "splash_potion{Potion:leaping}",
    "Water Breathing Splash (6:00) Potion": "splash_potion{Potion:long_water_breathing}",
    "Invisibility Splash (6:00) Potion": "splash_potion{Potion:long_invisibility}",
    "Regeneration II Splash (0:45) Potion": "splash_potion{Potion:strong_regeneration}",
    "Swiftness II Splash (3:00) Potion": "splash_potion{Potion:strong_swiftness}",
    "Poison II Splash (0:45) Potion": "splash_potion{Potion:strong_poison}",
    "Strength II Splash (3:00) Potion": "splash_potion{Potion:strong_strength}",
    "Splash Turtle Master Potion (0:20)": "splash_potion{Potion:turtle_master}",
    "Splash Turtle Master Potion (0:40)": "splash_potion{Potion:long_turtle_master}",
    "Splash Turtle Master Potion II (0:20)": "splash_potion{Potion:strong_turtle_master}",
    "Splash Slow Falling Potion (1:30)": "splash_potion{Potion:slow_falling}",
    "Splash Slow Falling Potion (4:00)": "splash_potion{Potion:long_slow_falling}",
    "Glass Bottle": "glass_bottle",
    "Spider Eye": "spider_eye",
    "Fermented Spider Eye": "fermented_spider_eye",
    "Blaze Powder": "blaze_powder",
    "Magma Cream": "magma_cream",
    "Brewing Stand": "brewing_stand",
    "Cauldron": "cauldron",
    "Eye of Ender": "ender_eye",
    "Glistering Melon Slice": "glistering_melon_slice",
    "Bat Spawn Egg": "bat_spawn_egg",
    "Blaze Spawn Egg": "blaze_spawn_egg",
    "Cave Spider Spawn Egg": "cave_spider_spawn_egg",
    "Chicken Spawn Egg": "chicken_spawn_egg",
    "Cod Spawn Egg": "cod_spawn_egg",
    "Cow Spawn Egg": "cow_spawn_egg",
    "Creeper Spawn Egg": "creeper_spawn_egg",
    "Dolphin Spawn Egg": "dolphin_spawn_egg",
    "Donkey Spawn Egg": "donkey_spawn_egg",
    "Drowned Spawn Egg": "drowned_spawn_egg",
    "Elder Guardian Spawn Egg": "elder_guardian_spawn_egg",
    "Enderman Spawn Egg": "enderman_spawn_egg",
    "Endermite Spawn Egg": "endermite_spawn_egg",
    "Evoker Spawn Egg": "evoker_spawn_egg",
    "Ghast Spawn Egg": "ghast_spawn_egg",
    "Guardian Spawn Egg": "guardian_spawn_egg",
    "Horse Spawn Egg": "horse_spawn_egg",
    "Husk Spawn Egg": "husk_spawn_egg",
    "Llama Spawn Egg": "llama_spawn_egg",
    "Magma Cube Spawn Egg": "magma_cube_spawn_egg",
    "Mooshroom Spawn Egg": "mooshroom_spawn_egg",
    "Mule Spawn Egg": "mule_spawn_egg",
    "Ocelot Spawn Egg": "ocelot_spawn_egg",
    "Parrot Spawn Egg": "parrot_spawn_egg",
    "Phantom Spawn Egg": "phantom_spawn_egg",
    "Pig Spawn Egg": "pig_spawn_egg",
    "Polar Bear Spawn Egg": "polar_bear_spawn_egg",
    "Pufferfish Spawn Egg": "pufferfish_spawn_egg",
    "Rabbit Spawn Egg": "rabbit_spawn_egg",
    "Salmon Spawn Egg": "salmon_spawn_egg",
    "Sheep Spawn Egg": "sheep_spawn_egg",
    "Shulker Spawn Egg": "shulker_spawn_egg",
    "Silverfish Spawn Egg": "silverfish_spawn_egg",
    "Skeleton Spawn Egg": "skeleton_spawn_egg",
    "Skeleton Horse Spawn Egg": "skeleton_horse_spawn_egg",
    "Slime Spawn Egg": "slime_spawn_egg",
    "Spider Spawn Egg": "spider_spawn_egg",
    "Squid Spawn Egg": "squid_spawn_egg",
    "Stray Spawn Egg": "stray_spawn_egg",
    "Tropical Fish Spawn Egg": "tropical_fish_spawn_egg",
    "Turtle Spawn Egg": "turtle_spawn_egg",
    "Vex Spawn Egg": "vex_spawn_egg",
    "Villager Spawn Egg": "villager_spawn_egg",
    "Vindicator Spawn Egg": "vindicator_spawn_egg",
    "Witch Spawn Egg": "witch_spawn_egg",
    "Wither Skeleton Spawn Egg": "wither_skeleton_spawn_egg",
    "Wolf Spawn Egg": "wolf_spawn_egg",
    "Zombie Spawn Egg": "zombie_spawn_egg",
    "Zombie Horse Spawn Egg": "zombie_horse_spawn_egg",
    "Zombie Pigman Spawn Egg": "zombie_pigman_spawn_egg",
    "Zombie Villager Spawn Egg": "zombie_villager_spawn_egg",
    "Bottle o' Enchanting": "experience_bottle",
    "Fire Charge": "fire_charge",
    "Book and Quill": "writable_book",
    "Written Book": "written_book",
    "Emerald": "emerald",
    "Item Frame": "item_frame",
    "Flower Pot": "flower_pot",
    "Carrot": "carrot",
    "Potato": "potato",
    "Baked Potato": "baked_potato",
    "Poisonous Potato": "poisonous_potato",
    "Empty Map": "map",
    "Golden Carrot": "golden_carrot",
    "Skeleton Skull": "skeleton_skull",
    "Wither Skeleton Skull": "wither_skeleton_skull",
    "Player Head": "player_head",
    "Zombie Head": "zombie_head",
    "Creeper Head": "creeper_head",
    "Dragon Head": "dragon_head",
    "Carrot on a Stick": "carrot_on_a_stick",
    "Nether Star": "nether_star",
    "Pumpkin Pie": "pumpkin_pie",
    "Firework Rocket": "firework_rocket",
    "Firework Star": "firework_star",
    "Enchanted Book": "enchanted_book",
    "Nether Brick": "nether_brick",
    "Nether Quartz": "quartz",
    "Minecart with TNT": "tnt_minecart",
    "Minecart with Hopper": "hopper_minecart",
    "Prismarine Shard": "prismarine_shard",
    "Prismarine Crystals": "prismarine_crystals",
    "Raw Rabbit": "rabbit",
    "Cooked Rabbit": "cooked_rabbit",
    "Rabbit Stew": "rabbit_stew",
    "Rabbit's Foot": "rabbit_foot",
    "Rabbit Hide": "rabbit_hide",
    "Armor Stand": "armor_stand",
    "Iron Horse Armor": "iron_horse_armor",
    "Golden Horse Armor": "golden_horse_armor",
    "Diamond Horse Armor": "diamond_horse_armor",
    "Lead": "lead",
    "Name Tag": "name_tag",
    "Minecart with Command Block": "command_block_minecart",
    "Raw Mutton": "mutton",
    "Cooked Mutton": "cooked_mutton",
    "White Banner": "white_banner",
    "Orange Banner": "orange_banner",
    "Magenta Banner": "magenta_banner",
    "Light Blue Banner": "light_blue_banner",
    "Yellow Banner": "yellow_banner",
    "Lime Banner": "lime_banner",
    "Pink Banner": "pink_banner",
    "Gray Banner": "gray_banner",
    "Light Gray Banner": "light_gray_banner",
    "Cyan Banner": "cyan_banner",
    "Purple Banner": "purple_banner",
    "Blue Banner": "blue_banner",
    "Brown Banner": "brown_banner",
    "Green Banner": "green_banner",
    "Red Banner": "red_banner",
    "Black Banner": "black_banner",
    "End Crystal": "end_crystal",
    "Chorus Fruit": "chorus_fruit",
    "Popped Chorus Fruit": "popped_chorus_fruit",
    "Beetroot": "beetroot",
    "Beetroot Seeds": "beetroot_seeds",
    "Beetroot Soup": "beetroot_soup",
    "Dragon's Breath": "dragon_breath",
    "Spectral Arrow": "spectral_arrow",
    "Tipped Arrow": "tipped_arrow",
    "Shield": "shield",
    "Elytra": "elytra",
    "Spruce Boat": "spruce_boat",
    "Birch Boat": "birch_boat",
    "Jungle Boat": "jungle_boat",
    "Acacia Boat": "acacia_boat",
    "Dark Oak Boat": "dark_oak_boat",
    "Totem of Undying": "totem_of_undying",
    "Shulker Shell": "shulker_shell",
    "Iron Nugget": "iron_nugget",
    "Knowledge Book": "knowledge_book",
    "Debug Stick": "debug_stick",
    "13 Disc": "music_disc_13",
    "Cat Disc": "music_disc_cat",
    "Blocks Disc": "music_disc_blocks",
    "Chirp Disc": "music_disc_chirp",
    "Far Disc": "music_disc_far",
    "Mall Disc": "music_disc_mall",
    "Mellohi Disc": "music_disc_mellohi",
    "Stal Disc": "music_disc_stal",
    "Strad Disc": "music_disc_strad",
    "Ward Disc": "music_disc_ward",
    "11 Disc": "music_disc_11",
    "Wait Disc": "music_disc_wait",
    "Trident": "trident",
    "Phantom Membrane": "phantom_membrane",
    "Nautilus Shell": "nautilus_shell",
    "Heart of the Sea": "heart_of_the_sea",
    "Water": "water",
    "Lava": "lava",
    "Tall Seagrass": "tall_seagrass",
    "Piston Head": "piston_head",
    "Moving Piston": "moving_piston",
    "Wall Torch": "wall_torch",
    "Fire": "fire",
    "Redstone Dust": "redstone_wire",
    "Wall Sign": "wall_sign",
    "Redstone Wall Torch": "redstone_wall_torch",
    "Nether Portal": "nether_portal",
    "Attached Pumpkin Stem": "attached_pumpkin_stem",
    "Attached Melon Stem": "attached_melon_stem",
    "Pumpkin Stem": "pumpkin_stem",
    "Melon Stem": "melon_stem",
    "End Portal": "end_portal",
    "Cocoa": "cocoa",
    "Tripwire": "tripwire",
    "Potted Oak Sapling": "potted_oak_sapling",
    "Potted Spruce Sapling": "potted_spruce_sapling",
    "Potted Birch Sapling": "potted_birch_sapling",
    "Potted Jungle Sapling": "potted_jungle_sapling",
    "Potted Acacia Sapling": "potted_acacia_sapling",
    "Potted Dark Oak Sapling": "potted_dark_oak_sapling",
    "Potted Fern": "potted_fern",
    "Potted Dandelion": "potted_dandelion",
    "Potted Poppy": "potted_poppy",
    "Potted Blue Orchid": "potted_blue_orchid",
    "Potted Allium": "potted_allium",
    "Potted Azure Bluet": "potted_azure_bluet",
    "Potted Red Tulip": "potted_red_tulip",
    "Potted Orange Tulip": "potted_orange_tulip",
    "Potted White Tulip": "potted_white_tulip",
    "Potted Pink Tulip": "potted_pink_tulip",
    "Potted Oxeye Daisy": "potted_oxeye_daisy",
    "Potted Red Mushroom": "potted_red_mushroom",
    "Potted Brown Mushroom": "potted_brown_mushroom",
    "Potted Dead Bush": "potted_dead_bush",
    "Potted Cactus": "potted_cactus",
    "Carrots": "carrots",
    "Potatoes": "potatoes",
    "Skeleton Wall Skull": "skeleton_wall_skull",
    "Wither Skeleton Wall Skull": "wither_skeleton_wall_skull",
    "Zombie Wall Head": "zombie_wall_head",
    "Player Wall Head": "player_wall_head",
    "Creeper Wall Head": "creeper_wall_head",
    "Dragon Wall Head": "dragon_wall_head",
    "White wall banner": "white_wall_banner",
    "Orange wall banner": "orange_wall_banner",
    "Magenta wall banner": "magenta_wall_banner",
    "Light blue wall banner": "light_blue_wall_banner",
    "Yellow wall banner": "yellow_wall_banner",
    "Lime wall banner": "lime_wall_banner",
    "Pink wall banner": "pink_wall_banner",
    "Gray wall banner": "gray_wall_banner",
    "Light gray wall banner": "light_gray_wall_banner",
    "Cyan wall banner": "cyan_wall_banner",
    "Purple wall banner": "purple_wall_banner",
    "Blue wall banner": "blue_wall_banner",
    "Brown wall banner": "brown_wall_banner",
    "Green wall banner": "green_wall_banner",
    "Red wall banner": "red_wall_banner",
    "Black wall banner": "black_wall_banner",
    "Beetroots": "beetroots",
    "End Gateway": "end_gateway",
    "Frosted Ice": "frosted_ice",
    "Kelp Plant": "kelp_plant",
    "Dead Tube Coral Wall Fan": "dead_tube_coral_wall_fan",
    "Dead Brain Coral Wall Fan": "dead_brain_coral_wall_fan",
    "Dead Bubble Coral Wall Fan": "dead_bubble_coral_wall_fan",
    "Dead Fire Coral Wall Fan": "dead_fire_coral_wall_fan",
    "Dead Horn Coral Wall Fan": "dead_horn_coral_wall_fan",
    "Tube Coral Wall Fan": "tube_coral_wall_fan",
    "Brain Coral Wall Fan": "brain_coral_wall_fan",
    "Bubble Coral Wall Fan": "bubble_coral_wall_fan",
    "Fire Coral Wall Fan": "fire_coral_wall_fan",
    "Horn Coral Wall Fan": "horn_coral_wall_fan",
    "Creeper Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"creeper"}}}',
    "Skeleton Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"skeleton"}}}',
    "Spider Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"spider"}}}',
    "Giant Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"giant"}}}',
    "Zombie Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"zombie"}}}',
    "Slime Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"slime"}}}',
    "Ghast Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"ghast"}}}',
    "Pig Zombie Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"zombie_pigman"}}}',
    "Enderman Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"enderman"}}}',
    "Cave Spider Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"cave_spider"}}}',
    "Silverfish Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"silverfish"}}}',
    "Blaze Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"blaze"}}}',
    "Magma Cube Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"magma_cube"}}}',
    "Ender Dragon Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"ender_dragon"}}}',
    "Wither Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"wither"}}}',
    "Bat Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"bat"}}}',
    "Witch Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"witch"}}}',
    "Pig Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"pig"}}}',
    "Sheep Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"sheep"}}}',
    "Cow Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"cow"}}}',
    "Chicken Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"chicken"}}}',
    "Squid Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"squid"}}}',
    "Wolf Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"wolf"}}}',
    "Mooshroom Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"mooshroom"}}}',
    "Snowman Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"snow_golem"}}}',
    "Ocelot Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"ocelot"}}}',
    "Iron Golem Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"iron_golem"}}}',
    "Horse Spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"horse"}}}',
    "Cornflower": "cornflower",
    "Lily of the Valley": "lily_of_the_valley",
    "Wither Rose": "wither_rose",
    "Smooth Stone Slab": "smooth_stone_slab",
    "Cut Sandstone Slab": "cut_sandstone_slab",
    "Cut Red Sandstone Slab": "cut_red_sandstone_slab",
    "Brick Wall": "brick_wall",
    "Prismarine Wall": "prismarine_wall",
    "Red Sandstone Wall": "red_sandstone_wall",
    "Mossy Stone Brick Wall": "mossy_stone_brick_wall",
    "Granite Wall": "granite_wall",
    "Stone Brick Wall": "stone_brick_wall",
    "Nether Brick Wall": "nether_brick_wall",
    "Andesite Wall": "andesite_wall",
    "Red Nether Brick Wall": "red_nether_brick_wall",
    "Sandstone Wall": "sandstone_wall",
    "End Stone Brick Wall": "end_stone_brick_wall",
    "Diorite Wall": "diorite_wall",
    "Polished Granite Stairs": "polished_granite_stairs",
    "Smooth Red Sandstone Stairs": "smooth_red_sandstone_stairs",
    "Mossy Stone Brick Stairs": "mossy_stone_brick_stairs",
    "Polished Diorite Stairs": "polished_diorite_stairs",
    "Mossy Cobblestone Stairs": "mossy_cobblestone_stairs",
    "End Stone Brick Stairs": "end_stone_brick_stairs",
    "Stone Stairs": "stone_stairs",
    "Smooth Sandstone Stairs": "smooth_sandstone_stairs",
    "Smooth Quartz Stairs": "smooth_quartz_stairs",
    "Granite Stairs": "granite_stairs",
    "Andesite Stairs": "andesite_stairs",
    "Red Nether Brick Stairs": "red_nether_brick_stairs",
    "Polished Andesite Stairs": "polished_andesite_stairs",
    "Diorite Stairs": "diorite_stairs",
    "Polished Granite Slab": "polished_granite_slab",
    "Smooth Red Sandstone Slab": "smooth_red_sandstone_slab",
    "Mossy Stone Brick Slab": "mossy_stone_brick_slab",
    "Polished Diorite Slab": "polished_diorite_slab",
    "Mossy Cobblestone Slab": "mossy_cobblestone_slab",
    "End Stone Brick Slab": "end_stone_brick_slab",
    "Smooth Sandstone Slab": "smooth_sandstone_slab",
    "Smooth Quartz Slab": "smooth_quartz_slab",
    "Granite Slab": "granite_slab",
    "Andesite Slab": "andesite_slab",
    "Red Nether Brick Slab": "red_nether_brick_slab",
    "Polished Andesite Slab": "polished_andesite_slab",
    "Diorite Slab": "diorite_slab",
    "Scaffolding": "scaffolding",
    "Jigsaw Block": "jigsaw",
    "Composter": "composter",
    "Oak Sign": "oak_sign",
    "Spruce Sign": "spruce_sign",
    "Birch Sign": "birch_sign",
    "Jungle Sign": "jungle_sign",
    "Acacia Sign": "acacia_sign",
    "Dark Oak Sign": "dark_oak_sign",
    "Bamboo": "bamboo",
    "Red Dye": "red_dye",
    "Green Dye": "green_dye",
    "Yellow Dye": "yellow_dye",
    "Blue Dye": "blue_dye",
    "Brown Dye": "brown_dye",
    "Black Dye": "black_dye",
    "White Dye": "white_dye",
    "Cat Spawn Egg": "cat_spawn_egg",
    "Fox Spawn Egg": "fox_spawn_egg",
    "Panda Spawn Egg": "panda_spawn_egg",
    "Pillager Spawn Egg": "pillager_spawn_egg",
    "Ravager Spawn Egg": "ravager_spawn_egg",
    "Trader Llama Spawn Egg": "trader_llama_spawn_egg",
    "Wandering Trader Spawn Egg": "wandering_trader_spawn_egg",
    "Leather Horse Armor": "leather_horse_armor",
    "Crossbow": "crossbow",
    "Suspicious Stew": "suspicious_stew",
    "Loom": "loom",
    "Banner Pattern": "piglin_banner_pattern",
    "Barrel": "barrel",
    "Smoker": "smoker",
    "Blast Furnace": "blast_furnace",
    "Cartography Table": "cartography_table",
    "Fletching Table": "fletching_table",
    "Grindstone": "grindstone",
    "Lectern": "lectern",
    "Smithing Table": "smithing_table",
    "Stonecutter": "stonecutter",
    "Bell": "bell",
    "Lantern": "lantern",
    "Sweet Berries": "sweet_berries",
    "Campfire": "campfire",
    "Bee Spawn Egg": "bee_spawn_egg",
    "Honeycomb": "honeycomb",
    "Bee Nest": "bee_nest",
    "Beehive": "beehive",
    "Honey Bottle": "honey_bottle",
    "Honey Block": "honey_block",
    "Honeycomb Block": "honeycomb_block",
    "Oak Wall Sign": "oak_wall_sign",
    "Spruce Wall Sign": "spruce_wall_sign",
    "Birch Wall Sign": "birch_wall_sign",
    "Acacia Wall Sign": "acacia_wall_sign",
    "Jungle Wall Sign": "jungle_wall_sign",
    "Dark Oak Wall Sign": "dark_oak_wall_sign",
    "Potted Cornflower": "potted_cornflower",
    "Potted Lily of the Valley": "potted_lily_of_the_valley",
    "Potted Wither Rose": "potted_wither_rose",
    "Bamboo Sapling": "bamboo_sapling",
    "Potted Bamboo": "potted_bamboo",
    "Sweet Berry Bush": "sweet_berry_bush",
    "Crimson Nylium": "crimson_nylium",
    "Warped Nylium": "warped_nylium",
    "Crimson Planks": "crimson_planks",
    "Warped Planks": "warped_planks",
    "Nether Gold Ore": "nether_gold_ore",
    "Crimson Stem": "crimson_stem",
    "Warped Stem": "warped_stem",
    "Stripped Crimson Stem": "stripped_crimson_stem",
    "Stripped Warped Stem": "stripped_warped_stem",
    "Stripped Crimson Hyphae": "stripped_crimson_hyphae",
    "Stripped Warped Hyphae": "stripped_warped_hyphae",
    "Crimson Hyphae": "crimson_hyphae",
    "Warped Hyphae": "warped_hyphae",
    "Crimson Fungus": "crimson_fungus",
    "Warped Fungus": "warped_fungus",
    "Crimson Roots": "crimson_roots",
    "Warped Roots": "warped_roots",
    "Nether Sprouts": "nether_sprouts",
    "Weeping Vines": "weeping_vines",
    "Twisting Vines": "twisting_vines",
    "Crimson Slab": "crimson_slab",
    "Warped Slab": "warped_slab",
    "Crimson Pressure Plate": "crimson_pressure_plate",
    "Warped Pressure Plate": "warped_pressure_plate",
    "Polished Blackstone Pressure Plate": "polished_blackstone_pressure_plate",
    "Crimson Fence": "crimson_fence",
    "Warped Fence": "warped_fence",
    "Soul Soil": "soul_soil",
    "Basalt": "basalt",
    "Polished Basalt": "polished_basalt",
    "Soul Torch": "soul_torch",
    "Crimson Trapdoor": "crimson_trapdoor",
    "Warped Trapdoor": "warped_trapdoor",
    "Chain": "chain",
    "Crimson Fence Gate": "crimson_fence_gate",
    "Warped Fence Gate": "warped_fence_gate",
    "Cracked Nether Bricks": "cracked_nether_bricks",
    "Chiseled Nether Bricks": "chiseled_nether_bricks",
    "Crimson Stairs": "crimson_stairs",
    "Warped Stairs": "warped_stairs",
    "Blackstone Wall": "blackstone_wall",
    "Polished Blackstone Wall": "polished_blackstone_wall",
    "Polished Blackstone Brick Wall": "polished_blackstone_brick_wall",
    "Crimson Button": "crimson_button",
    "Warped Button": "warped_button",
    "Polished Blackstone Button": "polished_blackstone_button",
    "Quartz Bricks": "quartz_bricks",
    "Warped Wart Block": "warped_wart_block",
    "Crimson Door": "crimson_door",
    "Warped Door": "warped_door",
    "Netherite Ingot": "netherite_ingot",
    "Netherite Scrap": "netherite_scrap",
    "Netherite Sword": "netherite_sword",
    "Netherite Shovel": "netherite_shovel",
    "Netherite Pickaxe": "netherite_pickaxe",
    "Netherite Axe": "netherite_axe",
    "Netherite Hoe": "netherite_hoe",
    "Netherite Helmet": "netherite_helmet",
    "Netherite Chestplate": "netherite_chestplate",
    "Netherite Leggings": "netherite_leggings",
    "Netherite Boots": "netherite_boots",
    "Crimson Sign": "crimson_sign",
    "Warped Sign": "warped_sign",
    "Hoglin Spawn Egg": "hoglin_spawn_egg",
    "Piglin Spawn Egg": "piglin_spawn_egg",
    "Strider Spawn Egg": "strider_spawn_egg",
    "Zoglin Spawn Egg": "zoglin_spawn_egg",
    "Zombified Piglin Spawn Egg": "zombified_piglin_spawn_egg",
    "Warped Fungus on a Stick": "warped_fungus_on_a_stick",
    "Music Disc": "music_disc_pigstep",
    "Soul Lantern": "soul_lantern",
    "Soul Campfire": "soul_campfire",
    "Shroomlight": "shroomlight",
    "Lodestone": "lodestone",
    "Block of Netherite": "netherite_block",
    "Ancient Debris": "ancient_debris",
    "Target": "target",
    "Crying Obsidian": "crying_obsidian",
    "Blackstone": "blackstone",
    "Blackstone Slab": "blackstone_slab",
    "Blackstone Stairs": "blackstone_stairs",
    "Gilded Blackstone": "gilded_blackstone",
    "Polished Blackstone": "polished_blackstone",
    "Polished Blackstone Slab": "polished_blackstone_slab",
    "Polished Blackstone Stairs": "polished_blackstone_stairs",
    "Chiseled Polished Blackstone": "chiseled_polished_blackstone",
    "Polished Blackstone Bricks": "polished_blackstone_bricks",
    "Polished Blackstone Brick Slab": "polished_blackstone_brick_slab",
    "Polished Blackstone Brick Stairs": "polished_blackstone_brick_stairs",
    "Cracked Polished Blackstone Bricks": "cracked_polished_blackstone_bricks",
    "Respawn Anchor": "respawn_anchor",
    "Soul Fire": "soul_fire",
    "Soul Wall Torch": "soul_wall_torch",
    "Weeping Vines Plant": "weeping_vines_plant",
    "Twisting Vines Plant": "twisting_vines_plant",
    "Crimson Wall Sign": "crimson_wall_sign",
    "Warped Wall Sign": "warped_wall_sign",
    "Potted Crimson Fungus": "potted_crimson_fungus",
    "Potted Warped Fungus": "potted_warped_fungus",
    "Potted Crimson Roots": "potted_crimson_roots",
    "Potted Warped Roots": "potted_warped_roots",
    "Block of Amethyst": "amethyst_block",
    "Amethyst Bud": "amethyst_bud",
    "Amethyst Cluster": "amethyst_cluster",
    "Amethyst Shard": "amethyst_shard",
    "Bucket of Axolotl": "axolotl_bucket",
    "Axolotl Spawn Egg": "axolotl_spawn_egg",
    "Azalea": "azalea",
    "Azalea Leaves": "azalea_leaves",
    "Big Dripleaf": "big_dripleaf",
    "Black Candle": "black_candle",
    "Blue Candle": "blue_candle",
    "Broken Elytra": "broken_elytra",
    "Brown Candle": "brown_candle",
    "Budding Amethyst": "budding_amethyst",
    "Bundle": "bundle",
    "Filled Bundle": "bundle_filled",
    "Calcite": "calcite",
    "Candle": "candle",
    "Chiseled Deepslate": "chiseled_deepslate",
    "Cobbled Deepslate": "cobbled_deepslate",
    "Cobbled Deepslate Slab": "cobbled_deepslate_slab",
    "Cobbled Deepslate Stairs": "cobbled_deepslate_stairs",
    "Cobbled Deepslate Wall": "cobbled_deepslate_wall",
    "Block of Copper": "copper_block",
    "Copper Ingot": "copper_ingot",
    "Copper Ore": "copper_ore",
    "Cracked Deepslate Bricks": "cracked_deepslate_bricks",
    "Cracked Deepslate Tiles": "cracked_deepslate_tiles",
    "Arrow Loaded Crossbow": "crossbow_arrow",
    "Firework Loaded Crossbow": "crossbow_firework",
    "Cut Copper": "cut_copper",
    "Cut Copper Slab": "cut_copper_slab",
    "Cut Copper Stairs": "cut_copper_stairs",
    "Cyan Candle": "cyan_candle",
    "Deepslate": "deepslate",
    "Deepslate Bricks": "deepslate_bricks",
    "Deepslate Brick Slab": "deepslate_brick_slab",
    "Deepslate Brick Stairs": "deepslate_brick_stairs",
    "Deepslate Brick Wall": "deepslate_brick_wall",
    "Deepslate Coal Ore": "deepslate_coal_ore",
    "Deepslate Copper Ore": "deepslate_copper_ore",
    "Deepslate Diamond Ore": "deepslate_diamond_ore",
    "Deepslate Emerald Ore": "deepslate_emerald_ore",
    "Deepslate Gold Ore": "deepslate_gold_ore",
    "Deepslate Iron Ore": "deepslate_iron_ore",
    "Deepslate Lapis Lazuli Ore": "deepslate_lapis_ore",
    "Deepslate Redstone Ore": "deepslate_redstone_ore",
    "Deepslate Tiles": "deepslate_tiles",
    "Deepslate Tile Slab": "deepslate_tile_slab",
    "Deepslate Tile Stairs": "deepslate_tile_stairs",
    "Deepslate Tile Wall": "deepslate_tile_wall",
    "Dirt Path": "dirt_path",
    "Dripstone Block": "dripstone_block",
    "Exposed Copper": "exposed_copper",
    "Exposed Cut Copper": "exposed_cut_copper",
    "Exposed Cut Copper Slab": "exposed_cut_copper_slab",
    "Exposed Cut Copper Stairs": "exposed_cut_copper_stairs",
    "Flowering Azalea": "flowering_azalea",
    "Flowering Azalea Leaves": "flowering_azalea_leaves",
    "Glow Berries": "glow_berries",
    "Glow Ink Sac": "glow_ink_sac",
    "Glow Item Frame": "glow_item_frame",
    "Glow Lichen": "glow_lichen",
    "Glow Squid Spawn Egg": "glow_squid_spawn_egg",
    "Goat Spawn Egg": "goat_spawn_egg",
    "Gray Candle": "gray_candle",
    "Green Candle": "green_candle",
    "Hanging Roots": "hanging_roots",
    "Infested Deepslate": "infested_deepslate",
    "Large Amethyst Bud": "large_amethyst_bud",
    "Lightning Rod": "lightning_rod",
    "Light Blue Candle": "light_blue_candle",
    "Light Gray Candle": "light_gray_candle",
    "Lime Candle": "lime_candle",
    "Magenta Candle": "magenta_candle",
    "Medium Amethyst Bud": "medium_amethyst_bud",
    "Moss Block": "moss_block",
    "Moss Carpet": "moss_carpet",
    "Orange Candle": "orange_candle",
    "Oxidized Copper": "oxidized_copper",
    "Oxidized Cut Copper": "oxidized_cut_copper",
    "Oxidized Cut Copper Slab": "oxidized_cut_copper_slab",
    "Oxidized Cut Copper Stairs": "oxidized_cut_copper_stairs",
    "Piglin Brute Spawn Egg": "piglin_brute_spawn_egg",
    "Pink Candle": "pink_candle",
    "Pointed Dripstone": "pointed_dripstone",
    "Polished Deepslate": "polished_deepslate",
    "Polished Deepslate Slab": "polished_deepslate_slab",
    "Polished Deepslate Stairs": "polished_deepslate_stairs",
    "Polished Deepslate Wall": "polished_deepslate_wall",
    "Powder Snow Bucket": "powder_snow_bucket",
    "Purple Candle": "purple_candle",
    "Raw Copper": "raw_copper",
    "Block of Raw Copper": "raw_copper_block",
    "Raw Gold": "raw_gold",
    "Block of Raw Gold": "raw_gold_block",
    "Raw Iron": "raw_iron",
    "Block of Raw Iron": "raw_iron_block",
    "Red Candle": "red_candle",
    "Rooted Dirt": "rooted_dirt",
    "Sculk Sensor": "sculk_sensor",
    "Small Amethyst Bud": "small_amethyst_bud",
    "Small Dripleaf": "small_dripleaf",
    "Smooth Basalt": "smooth_basalt",
    "Spore Blossom": "spore_blossom",
    "Spyglass": "spyglass",
    "Tinted Glass": "tinted_glass",
    "Tuff": "tuff",
    "Waxed Block of Copper": "waxed_copper_block",
    "Waxed Cut Copper": "waxed_cut_copper",
    "Waxed Cut Copper Slab": "waxed_cut_copper_slab",
    "Waxed Cut Copper Stairs": "waxed_cut_copper_stairs",
    "Waxed Exposed Copper": "waxed_exposed_copper",
    "Waxed Exposed Cut Copper": "waxed_exposed_cut_copper",
    "Waxed Exposed Cut Copper Slab": "waxed_exposed_cut_copper_slab",
    "Waxed Exposed Cut Copper Stairs": "waxed_exposed_cut_copper_stairs",
    "Waxed Oxidized Copper": "waxed_oxidized_copper",
    "Waxed Oxidized Cut Copper": "waxed_oxidized_cut_copper",
    "Waxed Oxidized Cut Copper Slab": "waxed_oxidized_cut_copper_slab",
    "Waxed Oxidized Cut Copper Stairs": "waxed_oxidized_cut_copper_stairs",
    "Waxed Weathered Copper": "waxed_weathered_copper",
    "Waxed Weathered Cut Copper": "waxed_weathered_cut_copper",
    "Waxed Weathered Cut Copper Slab": "waxed_weathered_cut_copper_slab",
    "Waxed Weathered Cut Copper Stairs": "waxed_weathered_cut_copper_stairs",
    "Weathered Copper": "weathered_copper",
    "Weathered Cut Copper": "weathered_cut_copper",
    "Weathered Cut Copper Slab": "weathered_cut_copper_slab",
    "Weathered Cut Copper Stairs": "weathered_cut_copper_stairs",
    "White Candle": "white_candle",
    "Yellow Candle": "yellow_candle",
    "Otherside Disc": "music_disc_otherside",
}
