mobs = {'Axolotl': 'axolotl', 
        'Bat': 'bat', 
        'Bee': 'bee', 
        'Blaze': 'blaze', 
        'Camel': 'camel', 
        'Cat': 'cat', 
        'Cave Spider': 'cave_spider', 
        'Chicken': 'chicken', 
        'Cod': 'cod', 
        'Cow': 'cow', 
        'Creeper': 'creeper', 
        'Dolphin': 'dolphin', 
        'Donkey': 'donkey', 
        'Drowned': 'drowned', 
        'Elder Guardian': 'elder_guardian', 
        'Ender Dragon': 'ender_dragon', 
        'Enderman': 'enderman', 
        'Endermite': 'endermite', 
        'Evoker': 'evoker', 
        'Fox': 'fox', 'Ghast': 
        'ghast', 'Giant': 'giant', 
        'Glow Squid': 'glow_squid', 
        'Goat': 'goat', 
        'Guardian': 'guardian', 
        'Hoglin': 'hoglin', 
        'Horse': 'horse', 
        'Husk': 'husk', 
        'Illusioner': 'illusioner', 
        'Iron Golem': 'iron_golem', 
        'Llama': 'llama', 
        'Magma Cube': 'magma_cube', 
        'Mooshroom': 'mooshroom', 
        'Mule': 'mule', 
        'Ocelot': 'ocelot', 
        'Panda': 'panda', 
        'Parrot': 'parrot', 
        'Phantom': 'phantom', 
        'Pig': 'pig', 
        'Piglin': 'piglin', 
        'Piglin Brute': 'piglin_brute', 
        'Pillager': 'pillager', 
        'Polar Bear': 'polar_bear', 
        'Pufferfish': 'pufferfish', 
        'Rabbit': 'rabbit', 
        'Ravager': 'ravager', 
        'Salmon': 'salmon', 
        'Sheep': 'sheep', 
        'Shulker': 'shulker', 
        'Silverfish': 'silverfish', 
        'Sniffer': 'sniffer', 
        'Skeleton': 'skeleton', 
        'Skeleton Horse': 'skeleton_horse', 
        'Slime': 'slime', 
        'Snow Golem': 'snow_golem', 
        'Spider': 'spider', 
        'Squid': 'squid', 
        'Stray': 'stray', 
        'Strider': 'strider', 
        'Trader Llama': 'trader_llama', 
        'Tropical Fish': 'tropical_fish', 
        'Turtle': 'turtle', 
        'Vex': 'vex', 
        'Villager': 'villager', 
        'Vindicator': 'vindicator', 
        'Wandering Trader': 'wandering_trader', 
        'Witch': 'witch', 
        'Wither': 'wither', 
        'Wither Skeleton': 'wither_skeleton', 
        'Wolf': 'wolf', 
        'Zoglin': 'zoglin', 
        'Zombie': 'zombie', 
        'Zombie Horse': 'zombie_horse', 
        'Zombie Villager': 'zombie_villager', 
        'Zombified Piglin': 'zombified_piglin', 
        'Allay': 'allay', 
        'Frog': 'frog', 
        'Tadpole': 'tadpole', 
        'Warden': 'warden'
    }