Itens = {
    "stone": "stone",
    "granite": "granite",
    "polished granite": "polished_granite",
    "diorite": "diorite",
    "polished diorite": "polished_diorite",
    "andesite": "andesite",
    "polished andesite": "polished_andesite",
    "grass block": "grass_block",
    "dirt": "dirt",
    "coarse dirt": "coarse_dirt",
    "podzol": "podzol",
    "cobblestone": "cobblestone",
    "oak planks": "oak_planks",
    "spruce planks": "spruce_planks",
    "birch planks": "birch_planks",
    "jungle planks": "jungle_planks",
    "acacia planks": "acacia_planks",
    "dark oak planks": "dark_oak_planks",
    "oak sapling": "oak_sapling",
    "spruce sapling": "spruce_sapling",
    "birch sapling": "birch_sapling",
    "jungle sapling": "jungle_sapling",
    "acacia sapling": "acacia_sapling",
    "dark oak sapling": "dark_oak_sapling",
    "bedrock": "bedrock",
    "sand": "sand",
    "red sand": "red_sand",
    "gravel": "gravel",
    "gold ore": "gold_ore",
    "iron ore": "iron_ore",
    "coal ore": "coal_ore",
    "oak log": "oak_log",
    "spruce log": "spruce_log",
    "birch log": "birch_log",
    "jungle log": "jungle_log",
    "acacia log": "acacia_log",
    "dark oak log": "dark_oak_log",
    "stripped oak log": "stripped_oak_log",
    "stripped spruce log": "stripped_spruce_log",
    "stripped birch log": "stripped_birch_log",
    "stripped jungle log": "stripped_jungle_log",
    "stripped acacia log": "stripped_acacia_log",
    "stripped dark oak log": "stripped_dark_oak_log",
    "stripped oak wood": "stripped_oak_wood",
    "stripped spruce wood": "stripped_spruce_wood",
    "stripped birch wood": "stripped_birch_wood",
    "stripped jungle wood": "stripped_jungle_wood",
    "stripped acacia wood": "stripped_acacia_wood",
    "stripped dark oak wood": "stripped_dark_oak_wood",
    "oak wood": "oak_wood",
    "spruce wood": "spruce_wood",
    "birch wood": "birch_wood",
    "jungle wood": "jungle_wood",
    "acacia wood": "acacia_wood",
    "dark oak wood": "dark_oak_wood",
    "oak leaves": "oak_leaves",
    "spruce leaves": "spruce_leaves",
    "birch leaves": "birch_leaves",
    "jungle leaves": "jungle_leaves",
    "acacia leaves": "acacia_leaves",
    "dark oak leaves": "dark_oak_leaves",
    "sponge": "sponge",
    "wet sponge": "wet_sponge",
    "glass": "glass",
    "lapis lazuli ore": "lapis_ore",
    "lapis lazuli block": "lapis_block",
    "dispenser": "dispenser",
    "sandstone": "sandstone",
    "chiseled sandstone": "chiseled_sandstone",
    "cut sandstone": "cut_sandstone",
    "note block": "note_block",
    "powered rail": "powered_rail",
    "detector rail": "detector_rail",
    "sticky piston": "sticky_piston",
    "cobweb": "cobweb",
    "grass": "grass",
    "fern": "fern",
    "dead bush": "dead_bush",
    "seagrass": "seagrass",
    "sea pickle": "sea_pickle",
    "piston": "piston",
    "white wool": "white_wool",
    "orange wool": "orange_wool",
    "magenta wool": "magenta_wool",
    "light blue wool": "light_blue_wool",
    "yellow wool": "yellow_wool",
    "lime wool": "lime_wool",
    "pink wool": "pink_wool",
    "gray wool": "gray_wool",
    "light gray wool": "light_gray_wool",
    "cyan wool": "cyan_wool",
    "purple wool": "purple_wool",
    "blue wool": "blue_wool",
    "brown wool": "brown_wool",
    "green wool": "green_wool",
    "red wool": "red_wool",
    "black wool": "black_wool",
    "dandelion": "dandelion",
    "poppy": "poppy",
    "blue orchid": "blue_orchid",
    "allium": "allium",
    "azure bluet": "azure_bluet",
    "red tulip": "red_tulip",
    "orange tulip": "orange_tulip",
    "white tulip": "white_tulip",
    "pink tulip": "pink_tulip",
    "oxeye daisy": "oxeye_daisy",
    "brown mushroom": "brown_mushroom",
    "red mushroom": "red_mushroom",
    "block of gold": "gold_block",
    "block of iron": "iron_block",
    "oak slab": "oak_slab",
    "spruce slab": "spruce_slab",
    "birch slab": "birch_slab",
    "jungle slab": "jungle_slab",
    "acacia slab": "acacia_slab",
    "dark oak slab": "dark_oak_slab",
    "stone slab": "stone_slab",
    "sandstone slab": "sandstone_slab",
    "petrified oak slab": "petrified_oak_slab",
    "cobblestone slab": "cobblestone_slab",
    "brick slab": "brick_slab",
    "stone brick slab": "stone_brick_slab",
    "nether brick slab": "nether_brick_slab",
    "quartz slab": "quartz_slab",
    "red sandstone slab": "red_sandstone_slab",
    "purpur slab": "purpur_slab",
    "prismarine slab": "prismarine_slab",
    "prismarine brick slab": "prismarine_brick_slab",
    "dark prismarine slab": "dark_prismarine_slab",
    "smooth quartz": "smooth_quartz",
    "smooth red sandstone": "smooth_red_sandstone",
    "smooth sandstone": "smooth_sandstone",
    "smooth stone": "smooth_stone",
    "bricks": "bricks",
    "tnt": "tnt",
    "bookshelf": "bookshelf",
    "mossy cobblestone": "mossy_cobblestone",
    "obsidian": "obsidian",
    "torch": "torch",
    "end rod": "end_rod",
    "chorus plant": "chorus_plant",
    "chorus flower": "chorus_flower",
    "purpur block": "purpur_block",
    "purpur pillar": "purpur_pillar",
    "purpur stairs": "purpur_stairs",
    "spawner": "spawner",
    "oak stairs": "oak_stairs",
    "chest": "chest",
    "diamond ore": "diamond_ore",
    "block of diamond": "diamond_block",
    "crafting table": "crafting_table",
    "farmland": "farmland",
    "furnace": "furnace",
    "ladder": "ladder",
    "rail": "rail",
    "cobblestone stairs": "cobblestone_stairs",
    "lever": "lever",
    "stone pressure plate": "stone_pressure_plate",
    "oak pressure plate": "oak_pressure_plate",
    "spruce pressure plate": "spruce_pressure_plate",
    "birch pressure plate": "birch_pressure_plate",
    "jungle pressure plate": "jungle_pressure_plate",
    "acacia pressure plate": "acacia_pressure_plate",
    "dark oak pressure plate": "dark_oak_pressure_plate",
    "redstone ore": "redstone_ore",
    "redstone torch": "redstone_torch",
    "stone button": "stone_button",
    "snow": "snow",
    "ice": "ice",
    "snow block": "snow_block",
    "cactus": "cactus",
    "clay": "clay_ball",
    "jukebox": "jukebox",
    "oak fence": "oak_fence",
    "spruce fence": "spruce_fence",
    "birch fence": "birch_fence",
    "jungle fence": "jungle_fence",
    "acacia fence": "acacia_fence",
    "dark oak fence": "dark_oak_fence",
    "pumpkin": "pumpkin",
    "carved pumpkin": "carved_pumpkin",
    "netherrack": "netherrack",
    "soul sand": "soul_sand",
    "glowstone": "glowstone",
    "jack o'lantern": "jack_o_lantern",
    "oak trapdoor": "oak_trapdoor",
    "spruce trapdoor": "spruce_trapdoor",
    "birch trapdoor": "birch_trapdoor",
    "jungle trapdoor": "jungle_trapdoor",
    "acacia trapdoor": "acacia_trapdoor",
    "dark oak trapdoor": "dark_oak_trapdoor",
    "infested stone": "infested_stone",
    "infested cobblestone": "infested_cobblestone",
    "infested stone bricks": "infested_stone_bricks",
    "infested mossy stone bricks": "infested_mossy_stone_bricks",
    "infested cracked stone bricks": "infested_cracked_stone_bricks",
    "infested chiseled stone bricks": "infested_chiseled_stone_bricks",
    "stone bricks": "stone_bricks",
    "mossy stone bricks": "mossy_stone_bricks",
    "cracked stone bricks": "cracked_stone_bricks",
    "chiseled stone bricks": "chiseled_stone_bricks",
    "brown mushroom block": "brown_mushroom_block",
    "red mushroom block": "red_mushroom_block",
    "mushroom stem": "mushroom_stem",
    "iron bars": "iron_bars",
    "glass pane": "glass_pane",
    "melon": "melon",
    "vines": "vine",
    "oak fence gate": "oak_fence_gate",
    "spruce fence gate": "spruce_fence_gate",
    "birch fence gate": "birch_fence_gate",
    "jungle fence gate": "jungle_fence_gate",
    "acacia fence gate": "acacia_fence_gate",
    "dark oak fence gate": "dark_oak_fence_gate",
    "brick stairs": "brick_stairs",
    "stone brick stairs": "stone_brick_stairs",
    "mycelium": "mycelium",
    "lily pad": "lily_pad",
    "nether bricks": "nether_bricks",
    "nether brick fence": "nether_brick_fence",
    "nether brick stairs": "nether_brick_stairs",
    "enchanting table": "enchanting_table",
    "end portal frame": "end_portal_frame",
    "end stone": "end_stone",
    "end stone bricks": "end_stone_bricks",
    "dragon egg": "dragon_egg",
    "redstone lamp": "redstone_lamp",
    "sandstone stairs": "sandstone_stairs",
    "emerald ore": "emerald_ore",
    "ender chest": "ender_chest",
    "tripwire hook": "tripwire_hook",
    "block of emerald": "emerald_block",
    "spruce stairs": "spruce_stairs",
    "birch stairs": "birch_stairs",
    "jungle stairs": "jungle_stairs",
    "command block": "command_block",
    "beacon": "beacon",
    "cobblestone wall": "cobblestone_wall",
    "mossy cobblestone wall": "mossy_cobblestone_wall",
    "oak button": "oak_button",
    "spruce button": "spruce_button",
    "birch button": "birch_button",
    "jungle button": "jungle_button",
    "acacia button": "acacia_button",
    "dark oak button": "dark_oak_button",
    "anvil": "anvil",
    "chipped anvil": "chipped_anvil",
    "damaged anvil": "damaged_anvil",
    "trapped chest": "trapped_chest",
    "light weighted pressure plate": "light_weighted_pressure_plate",
    "heavy weighted pressure plate": "heavy_weighted_pressure_plate",
    "daylight detector": "daylight_detector",
    "block of redstone": "redstone_block",
    "nether quartz ore": "nether_quartz_ore",
    "hopper": "hopper",
    "chiseled quartz block": "chiseled_quartz_block",
    "block of quartz": "quartz_block",
    "quartz pillar": "quartz_pillar",
    "quartz stairs": "quartz_stairs",
    "activator rail": "activator_rail",
    "dropper": "dropper",
    "white terracotta": "white_terracotta",
    "orange terracotta": "orange_terracotta",
    "magenta terracotta": "magenta_terracotta",
    "light blue terracotta": "light_blue_terracotta",
    "yellow terracotta": "yellow_terracotta",
    "lime terracotta": "lime_terracotta",
    "pink terracotta": "pink_terracotta",
    "gray terracotta": "gray_terracotta",
    "light gray terracotta": "light_gray_terracotta",
    "cyan terracotta": "cyan_terracotta",
    "purple terracotta": "purple_terracotta",
    "blue terracotta": "blue_terracotta",
    "brown terracotta": "brown_terracotta",
    "green terracotta": "green_terracotta",
    "red terracotta": "red_terracotta",
    "black terracotta": "black_terracotta",
    "barrier": "barrier",
    "iron trapdoor": "iron_trapdoor",
    "hay bale": "hay_block",
    "white carpet": "white_carpet",
    "orange carpet": "orange_carpet",
    "magenta carpet": "magenta_carpet",
    "light blue carpet": "light_blue_carpet",
    "yellow carpet": "yellow_carpet",
    "lime carpet": "lime_carpet",
    "pink carpet": "pink_carpet",
    "gray carpet": "gray_carpet",
    "light gray carpet": "light_gray_carpet",
    "cyan carpet": "cyan_carpet",
    "purple carpet": "purple_carpet",
    "blue carpet": "blue_carpet",
    "brown carpet": "brown_carpet",
    "green carpet": "green_carpet",
    "red carpet": "red_carpet",
    "black carpet": "black_carpet",
    "terracotta": "terracotta",
    "block of coal": "coal_block",
    "packed ice": "packed_ice",
    "acacia stairs": "acacia_stairs",
    "dark oak stairs": "dark_oak_stairs",
    "slime block": "slime_block",
    "grass path": "grass_path",
    "sunflower": "sunflower",
    "lilac": "lilac",
    "rose bush": "rose_bush",
    "peony": "peony",
    "tall grass": "tall_grass",
    "large fern": "large_fern",
    "white stained glass": "white_stained_glass",
    "orange stained glass": "orange_stained_glass",
    "magenta stained glass": "magenta_stained_glass",
    "light blue stained glass": "light_blue_stained_glass",
    "yellow stained glass": "yellow_stained_glass",
    "lime stained glass": "lime_stained_glass",
    "pink stained glass": "pink_stained_glass",
    "gray stained glass": "gray_stained_glass",
    "light gray stained glass": "light_gray_stained_glass",
    "cyan stained glass": "cyan_stained_glass",
    "purple stained glass": "purple_stained_glass",
    "blue stained glass": "blue_stained_glass",
    "brown stained glass": "brown_stained_glass",
    "green stained glass": "green_stained_glass",
    "red stained glass": "red_stained_glass",
    "black stained glass": "black_stained_glass",
    "white stained glass pane": "white_stained_glass_pane",
    "orange stained glass pane": "orange_stained_glass_pane",
    "magenta stained glass pane": "magenta_stained_glass_pane",
    "light blue stained glass pane": "light_blue_stained_glass_pane",
    "yellow stained glass pane": "yellow_stained_glass_pane",
    "lime stained glass pane": "lime_stained_glass_pane",
    "pink stained glass pane": "pink_stained_glass_pane",
    "gray stained glass pane": "gray_stained_glass_pane",
    "light gray stained glass pane": "light_gray_stained_glass_pane",
    "cyan stained glass pane": "cyan_stained_glass_pane",
    "purple stained glass pane": "purple_stained_glass_pane",
    "blue stained glass pane": "blue_stained_glass_pane",
    "brown stained glass pane": "brown_stained_glass_pane",
    "green stained glass pane": "green_stained_glass_pane",
    "red stained glass pane": "red_stained_glass_pane",
    "black stained glass pane": "black_stained_glass_pane",
    "prismarine": "prismarine",
    "prismarine bricks": "prismarine_bricks",
    "dark prismarine": "dark_prismarine",
    "prismarine stairs": "prismarine_stairs",
    "prismarine brick stairs": "prismarine_brick_stairs",
    "dark prismarine stairs": "dark_prismarine_stairs",
    "sea lantern": "sea_lantern",
    "red sandstone": "red_sandstone",
    "chiseled red sandstone": "chiseled_red_sandstone",
    "cut red sandstone": "cut_red_sandstone",
    "red sandstone stairs": "red_sandstone_stairs",
    "repeating command block": "repeating_command_block",
    "chain command block": "chain_command_block",
    "magma block": "magma_block",
    "nether wart block": "nether_wart_block",
    "red nether bricks": "red_nether_bricks",
    "bone block": "bone_block",
    "structure void": "structure_void",
    "observer": "observer",
    "shulker box": "shulker_box",
    "white shulker box": "white_shulker_box",
    "orange shulker box": "orange_shulker_box",
    "magenta shulker box": "magenta_shulker_box",
    "light blue shulker box": "light_blue_shulker_box",
    "yellow shulker box": "yellow_shulker_box",
    "lime shulker box": "lime_shulker_box",
    "pink shulker box": "pink_shulker_box",
    "gray shulker box": "gray_shulker_box",
    "light gray shulker box": "light_gray_shulker_box",
    "cyan shulker box": "cyan_shulker_box",
    "purple shulker box": "purple_shulker_box",
    "blue shulker box": "blue_shulker_box",
    "brown shulker box": "brown_shulker_box",
    "green shulker box": "green_shulker_box",
    "red shulker box": "red_shulker_box",
    "black shulker box": "black_shulker_box",
    "white glazed terracotta": "white_glazed_terracotta",
    "orange glazed terracotta": "orange_glazed_terracotta",
    "magenta glazed terracotta": "magenta_glazed_terracotta",
    "light blue glazed terracotta": "light_blue_glazed_terracotta",
    "yellow glazed terracotta": "yellow_glazed_terracotta",
    "lime glazed terracotta": "lime_glazed_terracotta",
    "pink glazed terracotta": "pink_glazed_terracotta",
    "gray glazed terracotta": "gray_glazed_terracotta",
    "light gray glazed terracotta": "light_gray_glazed_terracotta",
    "cyan glazed terracotta": "cyan_glazed_terracotta",
    "purple glazed terracotta": "purple_glazed_terracotta",
    "blue glazed terracotta": "blue_glazed_terracotta",
    "brown glazed terracotta": "brown_glazed_terracotta",
    "green glazed terracotta": "green_glazed_terracotta",
    "red glazed terracotta": "red_glazed_terracotta",
    "black glazed terracotta": "black_glazed_terracotta",
    "white concrete": "white_concrete",
    "orange concrete": "orange_concrete",
    "magenta concrete": "magenta_concrete",
    "light blue concrete": "light_blue_concrete",
    "yellow concrete": "yellow_concrete",
    "lime concrete": "lime_concrete",
    "pink concrete": "pink_concrete",
    "gray concrete": "gray_concrete",
    "light gray concrete": "light_gray_concrete",
    "cyan concrete": "cyan_concrete",
    "purple concrete": "purple_concrete",
    "blue concrete": "blue_concrete",
    "brown concrete": "brown_concrete",
    "green concrete": "green_concrete",
    "red concrete": "red_concrete",
    "black concrete": "black_concrete",
    "white concrete powder": "white_concrete_powder",
    "orange concrete powder": "orange_concrete_powder",
    "magenta concrete powder": "magenta_concrete_powder",
    "light blue concrete powder": "light_blue_concrete_powder",
    "yellow concrete powder": "yellow_concrete_powder",
    "lime concrete powder": "lime_concrete_powder",
    "pink concrete powder": "pink_concrete_powder",
    "gray concrete powder": "gray_concrete_powder",
    "light gray concrete powder": "light_gray_concrete_powder",
    "cyan concrete powder": "cyan_concrete_powder",
    "purple concrete powder": "purple_concrete_powder",
    "blue concrete powder": "blue_concrete_powder",
    "brown concrete powder": "brown_concrete_powder",
    "green concrete powder": "green_concrete_powder",
    "red concrete powder": "red_concrete_powder",
    "black concrete powder": "black_concrete_powder",
    "turtle egg": "turtle_egg",
    "dead tube coral block": "dead_tube_coral_block",
    "dead brain coral block": "dead_brain_coral_block",
    "dead bubble coral block": "dead_bubble_coral_block",
    "dead fire coral block": "dead_fire_coral_block",
    "dead horn coral block": "dead_horn_coral_block",
    "tube coral block": "tube_coral_block",
    "brain coral block": "brain_coral_block",
    "bubble coral block": "bubble_coral_block",
    "fire coral block": "fire_coral_block",
    "horn coral block": "horn_coral_block",
    "tube coral": "tube_coral",
    "brain coral": "brain_coral",
    "bubble coral": "bubble_coral",
    "fire coral": "fire_coral",
    "horn coral": "horn_coral",
    "dead brain coral": "dead_brain_coral",
    "dead bubble coral": "dead_bubble_coral",
    "dead fire coral": "dead_fire_coral",
    "dead horn coral": "dead_horn_coral",
    "dead tube coral": "dead_tube_coral",
    "tube coral fan": "tube_coral_fan",
    "brain coral fan": "brain_coral_fan",
    "bubble coral fan": "bubble_coral_fan",
    "fire coral fan": "fire_coral_fan",
    "horn coral fan": "horn_coral_fan",
    "dead tube coral fan": "dead_tube_coral_fan",
    "dead brain coral fan": "dead_brain_coral_fan",
    "dead bubble coral fan": "dead_bubble_coral_fan",
    "dead fire coral fan": "dead_fire_coral_fan",
    "dead horn coral fan": "dead_horn_coral_fan",
    "blue ice": "blue_ice",
    "conduit": "conduit",
    "iron door": "iron_door",
    "oak door": "oak_door",
    "spruce door": "spruce_door",
    "birch door": "birch_door",
    "jungle door": "jungle_door",
    "acacia door": "acacia_door",
    "dark oak door": "dark_oak_door",
    "redstone repeater": "repeater",
    "redstone comparator": "comparator",
    "structure block": "structure_block",
    "turtle shell": "turtle_helmet",
    "scute": "scute",
    "iron shovel": "iron_shovel",
    "iron pickaxe": "iron_pickaxe",
    "iron axe": "iron_axe",
    "flint and steel": "flint_and_steel",
    "apple": "apple",
    "bow": "bow",
    "arrow": "arrow",
    "coal": "coal",
    "charcoal": "charcoal",
    "diamond": "diamond",
    "iron ingot": "iron_ingot",
    "gold ingot": "gold_ingot",
    "iron sword": "iron_sword",
    "wooden sword": "wooden_sword",
    "wooden shovel": "wooden_shovel",
    "wooden pickaxe": "wooden_pickaxe",
    "wooden axe": "wooden_axe",
    "stone sword": "stone_sword",
    "stone shovel": "stone_shovel",
    "stone pickaxe": "stone_pickaxe",
    "stone axe": "stone_axe",
    "diamond sword": "diamond_sword",
    "diamond shovel": "diamond_shovel",
    "diamond pickaxe": "diamond_pickaxe",
    "diamond axe": "diamond_axe",
    "stick": "stick",
    "bowl": "bowl",
    "mushroom stew": "mushroom_stew",
    "golden sword": "golden_sword",
    "golden shovel": "golden_shovel",
    "golden pickaxe": "golden_pickaxe",
    "golden axe": "golden_axe",
    "string": "string",
    "feather": "feather",
    "gunpowder": "gunpowder",
    "wooden hoe": "wooden_hoe",
    "stone hoe": "stone_hoe",
    "iron hoe": "iron_hoe",
    "diamond hoe": "diamond_hoe",
    "golden hoe": "golden_hoe",
    "wheat seeds": "wheat_seeds",
    "wheat": "wheat",
    "bread": "bread",
    "leather cap": "leather_helmet",
    "leather tunic": "leather_chestplate",
    "leather pants": "leather_leggings",
    "leather boots": "leather_boots",
    "chainmail helmet": "chainmail_helmet",
    "chainmail chestplate": "chainmail_chestplate",
    "chainmail leggings": "chainmail_leggings",
    "chainmail boots": "chainmail_boots",
    "iron helmet": "iron_helmet",
    "iron chestplate": "iron_chestplate",
    "iron leggings": "iron_leggings",
    "iron boots": "iron_boots",
    "diamond helmet": "diamond_helmet",
    "diamond chestplate": "diamond_chestplate",
    "diamond leggings": "diamond_leggings",
    "diamond boots": "diamond_boots",
    "golden helmet": "golden_helmet",
    "golden chestplate": "golden_chestplate",
    "golden leggings": "golden_leggings",
    "golden boots": "golden_boots",
    "flint": "flint",
    "raw porkchop": "porkchop",
    "cooked porkchop": "cooked_porkchop",
    "painting": "painting",
    "golden apple": "golden_apple",
    "enchanted golden apple": "enchanted_golden_apple",
    "sign": "sign",
    "bucket": "bucket",
    "water bucket": "water_bucket",
    "lava bucket": "lava_bucket",
    "minecart": "minecart",
    "saddle": "saddle",
    "redstone": "redstone",
    "snowball": "snowball",
    "oak boat": "oak_boat",
    "leather": "leather",
    "milk bucket": "milk_bucket",
    "bucket of pufferfish": "pufferfish_bucket",
    "bucket of salmon": "salmon_bucket",
    "bucket of cod": "cod_bucket",
    "bucket of tropical fish": "tropical_fish_bucket",
    "brick": "brick",
    "sugar cane": "sugar_cane",
    "kelp": "kelp",
    "dried kelp block": "dried_kelp_block",
    "paper": "paper",
    "book": "book",
    "slimeball": "slime_ball",
    "minecart with chest": "chest_minecart",
    "minecart with furnace": "furnace_minecart",
    "egg": "egg",
    "compass": "compass",
    "fishing rod": "fishing_rod",
    "clock": "clock",
    "glowstone dust": "glowstone_dust",
    "raw cod": "cod",
    "raw salmon": "salmon",
    "tropical fish": "tropical_fish",
    "pufferfish": "pufferfish",
    "cooked cod": "cooked_cod",
    "cooked salmon": "cooked_salmon",
    "ink sac": "ink_sac",
    "rose red": "rose_red",
    "cactus green": "cactus_green",
    "cocoa beans": "cocoa_beans",
    "lapis lazuli": "lapis_lazuli",
    "purple dye": "purple_dye",
    "cyan dye": "cyan_dye",
    "light gray dye": "light_gray_dye",
    "gray dye": "gray_dye",
    "pink dye": "pink_dye",
    "lime dye": "lime_dye",
    "dandelion yellow": "dandelion_yellow",
    "light blue dye": "light_blue_dye",
    "magenta dye": "magenta_dye",
    "orange dye": "orange_dye",
    "bone meal": "bone_meal",
    "bone": "bone",
    "sugar": "sugar",
    "cake": "cake",
    "white bed": "white_bed",
    "orange bed": "orange_bed",
    "magenta bed": "magenta_bed",
    "light blue bed": "light_blue_bed",
    "yellow bed": "yellow_bed",
    "lime bed": "lime_bed",
    "pink bed": "pink_bed",
    "gray bed": "gray_bed",
    "light gray bed": "light_gray_bed",
    "cyan bed": "cyan_bed",
    "purple bed": "purple_bed",
    "blue bed": "blue_bed",
    "brown bed": "brown_bed",
    "green bed": "green_bed",
    "red bed": "red_bed",
    "black bed": "black_bed",
    "cookie": "cookie",
    "map": "filled_map",
    "shears": "shears",
    "melon slice": "melon_slice",
    "dried kelp": "dried_kelp",
    "pumpkin seeds": "pumpkin_seeds",
    "melon seeds": "melon_seeds",
    "raw beef": "beef",
    "steak": "cooked_beef",
    "raw chicken": "chicken",
    "cooked chicken": "cooked_chicken",
    "rotten flesh": "rotten_flesh",
    "ender pearl": "ender_pearl",
    "blaze rod": "blaze_rod",
    "ghast tear": "ghast_tear",
    "gold nugget": "gold_nugget",
    "nether wart": "nether_wart",
    "potion": "potion",
    "splash potion": "splash_potion",
    "lingering potion": "lingering_potion",
    "water bottle": "potion{Potion:water}",
    "uncraftable potion": "potion{Potion:empty}",
    "awkward potion": "potion{Potion:awkward}",
    "thick potion": "potion{Potion:thick}",
    "mundane potion": "potion{Potion:mundane}",
    "regeneration potion (0:45)": "potion{Potion:regeneration}",
    "swiftness potion (3:00)": "potion{Potion:swiftness}",
    "fire resistance potion (3:00)": "potion{Potion:fire_resistance}",
    "poison potion (0:45)": "potion{Potion:poison}",
    "healing potion": "potion{Potion:healing}",
    "night vision potion (3:00)": "potion{Potion:night_vision}",
    "weakness potion (1:30)": "potion{Potion:weakness}",
    "strength potion (3:00)": "potion{Potion:strength}",
    "slowness potion (1:30)": "potion{Potion:slowness}",
    "harming potion": "potion{Potion:harming}",
    "water breathing potion (3:00)": "potion{Potion:water_breathing}",
    "invisibility potion (3:00)": "potion{Potion:invisibility}",
    "regeneration potion ii (0:22)": "potion{Potion:strong_regeneration}",
    "swiftness potion ii (1:30)": "potion{Potion:strong_swiftness}",
    "poison potion ii (0:22)": "potion{Potion:strong_poison}",
    "healing potion ii": "potion{Potion:strong_healing}",
    "strength potion ii (1:30)": "potion{Potion:strong_strength}",
    "leaping potion ii (1:30)": "potion{Potion:strong_leaping}",
    "harming potion ii": "potion{Potion:strong_harming}",
    "regeneration potion (2:00)": "potion{Potion:long_regeneration}",
    "swiftness potion (8:00)": "potion{Potion:long_swiftness}",
    "fire resistance potion (8:00)": "potion{Potion:long_fire_resistance}",
    "poison potion (2:00)": "potion{Potion:long_poison}",
    "night vision potion (8:00)": "potion{Potion:long_night_vision}",
    "weakness potion (4:00)": "potion{Potion:long_weakness}",
    "strength potion (8:00)": "potion{Potion:long_strength}",
    "slowness potion (4:00)": "potion{Potion:long_slowness}",
    "leaping potion (3:00)": "potion{Potion:leaping}",
    "water breathing potion (8:00)": "potion{Potion:long_water_breathing}",
    "invisibility potion (8:00)": "potion{Potion:long_invisibility}",
    "regeneration potion ii (1:00)": "potion{Potion:strong_regeneration}",
    "swiftness potion ii (4:00)": "potion{Potion:strong_swiftness}",
    "poison potion ii (1:00)": "potion{Potion:strong_poison}",
    "strength potion ii (4:00)": "potion{Potion:strong_strength}",
    "potion of the turtle master (0:20)": "potion{Potion:turtle_master}",
    "potion of the turtle master (0:40)": "potion{Potion:long_turtle_master}",
    "potion of the turtle master ii (0:20)": "potion{Potion:strong_turtle_master}",
    "potion of slow falling (1:30)": "potion{Potion:slow_falling}",
    "potion of slow falling (4:00)": "potion{Potion:long_slow_falling}",
    "regeneration splash (0:33) potion": "splash_potion{Potion:regeneration}",
    "swiftness splash (2:15) potion": "splash_potion{Potion:swiftness}",
    "fire resistance splash (2:15) potion": "splash_potion{Potion:fire_resistance}",
    "poison splash (0:33) potion": "splash_potion{Potion:poison}",
    "healing splash potion": "splash_potion{Potion:healing}",
    "night vision splash (2:15) potion": "splash_potion{Potion:night_vision}",
    "weakness splash (1:07) potion": "splash_potion{Potion:weakness}",
    "strength splash (2:15) potion": "splash_potion{Potion:strength}",
    "slowness splash (1:07) potion": "splash_potion{Potion:slowness}",
    "harming splash potion": "splash_potion{Potion:harming}",
    "water breathing splash (2:15) potion": "splash_potion{Potion:water_breathing}",
    "invisibility splash (2:15) potion": "splash_potion{Potion:invisibility}",
    "regeneration ii splash (0:16) potion": "splash_potion{Potion:strong_regeneration}",
    "swiftness ii splash (1:07) potion": "splash_potion{Potion:strong_swiftness}",
    "poison ii splash (0:16) potion": "splash_potion{Potion:strong_poison}",
    "healing ii splash potion": "splash_potion{Potion:strong_healing}",
    "strength ii splash (1:07) potion": "splash_potion{Potion:strong_poison}",
    "leaping ii splash (1:07) potion": "splash_potion{Potion:strong_leaping}",
    "harming ii splash potion": "splash_potion{Potion:strong_harming}",
    "regeneration splash (1:30) potion": "splash_potion{Potion:long_regeneration}",
    "swiftness splash (6:00) potion": "splash_potion{Potion:long_swiftness}",
    "fire resistance splash (6:00) potion": "splash_potion{Potion:long_fire_resistance}",
    "poison splash (1:30) potion": "splash_potion{Potion:long_poison}",
    "night vision splash (6:00) potion": "splash_potion{Potion:long_night_vision}",
    "weakness splash (3:00) potion": "splash_potion{Potion:long_weakness}",
    "strength splash (6:00) potion": "splash_potion{Potion:long_strength}",
    "slowness splash (3:00) potion": "splash_potion{Potion:long_slowness}",
    "leaping splash (2:15) potion": "splash_potion{Potion:leaping}",
    "water breathing splash (6:00) potion": "splash_potion{Potion:long_water_breathing}",
    "invisibility splash (6:00) potion": "splash_potion{Potion:long_invisibility}",
    "regeneration ii splash (0:45) potion": "splash_potion{Potion:strong_regeneration}",
    "swiftness ii splash (3:00) potion": "splash_potion{Potion:strong_swiftness}",
    "poison ii splash (0:45) potion": "splash_potion{Potion:strong_poison}",
    "strength ii splash (3:00) potion": "splash_potion{Potion:strong_strength}",
    "splash turtle master potion (0:20)": "splash_potion{Potion:turtle_master}",
    "splash turtle master potion (0:40)": "splash_potion{Potion:long_turtle_master}",
    "splash turtle master potion ii (0:20)": "splash_potion{Potion:strong_turtle_master}",
    "splash slow falling potion (1:30)": "splash_potion{Potion:slow_falling}",
    "splash slow falling potion (4:00)": "splash_potion{Potion:long_slow_falling}",
    "glass bottle": "glass_bottle",
    "spider eye": "spider_eye",
    "fermented spider eye": "fermented_spider_eye",
    "blaze powder": "blaze_powder",
    "magma cream": "magma_cream",
    "brewing stand": "brewing_stand",
    "cauldron": "cauldron",
    "eye of ender": "ender_eye",
    "glistering melon slice": "glistering_melon_slice",
    "bat spawn egg": "bat_spawn_egg",
    "blaze spawn egg": "blaze_spawn_egg",
    "cave spider spawn egg": "cave_spider_spawn_egg",
    "chicken spawn egg": "chicken_spawn_egg",
    "cod spawn egg": "cod_spawn_egg",
    "cow spawn egg": "cow_spawn_egg",
    "creeper spawn egg": "creeper_spawn_egg",
    "dolphin spawn egg": "dolphin_spawn_egg",
    "donkey spawn egg": "donkey_spawn_egg",
    "drowned spawn egg": "drowned_spawn_egg",
    "elder guardian spawn egg": "elder_guardian_spawn_egg",
    "enderman spawn egg": "enderman_spawn_egg",
    "endermite spawn egg": "endermite_spawn_egg",
    "evoker spawn egg": "evoker_spawn_egg",
    "ghast spawn egg": "ghast_spawn_egg",
    "guardian spawn egg": "guardian_spawn_egg",
    "horse spawn egg": "horse_spawn_egg",
    "husk spawn egg": "husk_spawn_egg",
    "llama spawn egg": "llama_spawn_egg",
    "magma cube spawn egg": "magma_cube_spawn_egg",
    "mooshroom spawn egg": "mooshroom_spawn_egg",
    "mule spawn egg": "mule_spawn_egg",
    "ocelot spawn egg": "ocelot_spawn_egg",
    "parrot spawn egg": "parrot_spawn_egg",
    "phantom spawn egg": "phantom_spawn_egg",
    "pig spawn egg": "pig_spawn_egg",
    "polar bear spawn egg": "polar_bear_spawn_egg",
    "pufferfish spawn egg": "pufferfish_spawn_egg",
    "rabbit spawn egg": "rabbit_spawn_egg",
    "salmon spawn egg": "salmon_spawn_egg",
    "sheep spawn egg": "sheep_spawn_egg",
    "shulker spawn egg": "shulker_spawn_egg",
    "silverfish spawn egg": "silverfish_spawn_egg",
    "skeleton spawn egg": "skeleton_spawn_egg",
    "skeleton horse spawn egg": "skeleton_horse_spawn_egg",
    "slime spawn egg": "slime_spawn_egg",
    "spider spawn egg": "spider_spawn_egg",
    "squid spawn egg": "squid_spawn_egg",
    "stray spawn egg": "stray_spawn_egg",
    "tropical fish spawn egg": "tropical_fish_spawn_egg",
    "turtle spawn egg": "turtle_spawn_egg",
    "vex spawn egg": "vex_spawn_egg",
    "villager spawn egg": "villager_spawn_egg",
    "vindicator spawn egg": "vindicator_spawn_egg",
    "witch spawn egg": "witch_spawn_egg",
    "wither skeleton spawn egg": "wither_skeleton_spawn_egg",
    "wolf spawn egg": "wolf_spawn_egg",
    "zombie spawn egg": "zombie_spawn_egg",
    "zombie horse spawn egg": "zombie_horse_spawn_egg",
    "zombie pigman spawn egg": "zombie_pigman_spawn_egg",
    "zombie villager spawn egg": "zombie_villager_spawn_egg",
    "bottle o' enchanting": "experience_bottle",
    "fire charge": "fire_charge",
    "book and quill": "writable_book",
    "written book": "written_book",
    "emerald": "emerald",
    "item frame": "item_frame",
    "flower pot": "flower_pot",
    "carrot": "carrot",
    "potato": "potato",
    "baked potato": "baked_potato",
    "poisonous potato": "poisonous_potato",
    "empty map": "map",
    "golden carrot": "golden_carrot",
    "skeleton skull": "skeleton_skull",
    "wither skeleton skull": "wither_skeleton_skull",
    "player head": "player_head",
    "zombie head": "zombie_head",
    "creeper head": "creeper_head",
    "dragon head": "dragon_head",
    "carrot on a stick": "carrot_on_a_stick",
    "nether star": "nether_star",
    "pumpkin pie": "pumpkin_pie",
    "firework rocket": "firework_rocket",
    "firework star": "firework_star",
    "enchanted book": "enchanted_book",
    "nether brick": "nether_brick",
    "nether quartz": "quartz",
    "minecart with tnt": "tnt_minecart",
    "minecart with hopper": "hopper_minecart",
    "prismarine shard": "prismarine_shard",
    "prismarine crystals": "prismarine_crystals",
    "raw rabbit": "rabbit",
    "cooked rabbit": "cooked_rabbit",
    "rabbit stew": "rabbit_stew",
    "rabbit's foot": "rabbit_foot",
    "rabbit hide": "rabbit_hide",
    "armor stand": "armor_stand",
    "iron horse armor": "iron_horse_armor",
    "golden horse armor": "golden_horse_armor",
    "diamond horse armor": "diamond_horse_armor",
    "lead": "lead",
    "name tag": "name_tag",
    "minecart with command block": "command_block_minecart",
    "raw mutton": "mutton",
    "cooked mutton": "cooked_mutton",
    "white banner": "white_banner",
    "orange banner": "orange_banner",
    "magenta banner": "magenta_banner",
    "light blue banner": "light_blue_banner",
    "yellow banner": "yellow_banner",
    "lime banner": "lime_banner",
    "pink banner": "pink_banner",
    "gray banner": "gray_banner",
    "light gray banner": "light_gray_banner",
    "cyan banner": "cyan_banner",
    "purple banner": "purple_banner",
    "blue banner": "blue_banner",
    "brown banner": "brown_banner",
    "green banner": "green_banner",
    "red banner": "red_banner",
    "black banner": "black_banner",
    "end crystal": "end_crystal",
    "chorus fruit": "chorus_fruit",
    "popped chorus fruit": "popped_chorus_fruit",
    "beetroot": "beetroot",
    "beetroot seeds": "beetroot_seeds",
    "beetroot soup": "beetroot_soup",
    "dragon's breath": "dragon_breath",
    "spectral arrow": "spectral_arrow",
    "tipped arrow": "tipped_arrow",
    "shield": "shield",
    "elytra": "elytra",
    "spruce boat": "spruce_boat",
    "birch boat": "birch_boat",
    "jungle boat": "jungle_boat",
    "acacia boat": "acacia_boat",
    "dark oak boat": "dark_oak_boat",
    "totem of undying": "totem_of_undying",
    "shulker shell": "shulker_shell",
    "iron nugget": "iron_nugget",
    "knowledge book": "knowledge_book",
    "debug stick": "debug_stick",
    "13 disc": "music_disc_13",
    "cat disc": "music_disc_cat",
    "blocks disc": "music_disc_blocks",
    "chirp disc": "music_disc_chirp",
    "far disc": "music_disc_far",
    "mall disc": "music_disc_mall",
    "mellohi disc": "music_disc_mellohi",
    "stal disc": "music_disc_stal",
    "strad disc": "music_disc_strad",
    "ward disc": "music_disc_ward",
    "11 disc": "music_disc_11",
    "wait disc": "music_disc_wait",
    "trident": "trident",
    "phantom membrane": "phantom_membrane",
    "nautilus shell": "nautilus_shell",
    "heart of the sea": "heart_of_the_sea",
    "water": "water",
    "lava": "lava",
    "tall seagrass": "tall_seagrass",
    "piston head": "piston_head",
    "moving piston": "moving_piston",
    "wall torch": "wall_torch",
    "fire": "fire",
    "redstone dust": "redstone_wire",
    "wall sign": "wall_sign",
    "redstone wall torch": "redstone_wall_torch",
    "nether portal": "nether_portal",
    "attached pumpkin stem": "attached_pumpkin_stem",
    "attached melon stem": "attached_melon_stem",
    "pumpkin stem": "pumpkin_stem",
    "melon stem": "melon_stem",
    "end portal": "end_portal",
    "cocoa": "cocoa",
    "tripwire": "tripwire",
    "potted oak sapling": "potted_oak_sapling",
    "potted spruce sapling": "potted_spruce_sapling",
    "potted birch sapling": "potted_birch_sapling",
    "potted jungle sapling": "potted_jungle_sapling",
    "potted acacia sapling": "potted_acacia_sapling",
    "potted dark oak sapling": "potted_dark_oak_sapling",
    "potted fern": "potted_fern",
    "potted dandelion": "potted_dandelion",
    "potted poppy": "potted_poppy",
    "potted blue orchid": "potted_blue_orchid",
    "potted allium": "potted_allium",
    "potted azure bluet": "potted_azure_bluet",
    "potted red tulip": "potted_red_tulip",
    "potted orange tulip": "potted_orange_tulip",
    "potted white tulip": "potted_white_tulip",
    "potted pink tulip": "potted_pink_tulip",
    "potted oxeye daisy": "potted_oxeye_daisy",
    "potted red mushroom": "potted_red_mushroom",
    "potted brown mushroom": "potted_brown_mushroom",
    "potted dead bush": "potted_dead_bush",
    "potted cactus": "potted_cactus",
    "carrots": "carrots",
    "potatoes": "potatoes",
    "skeleton wall skull": "skeleton_wall_skull",
    "wither skeleton wall skull": "wither_skeleton_wall_skull",
    "zombie wall head": "zombie_wall_head",
    "player wall head": "player_wall_head",
    "creeper wall head": "creeper_wall_head",
    "dragon wall head": "dragon_wall_head",
    "white wall banner": "white_wall_banner",
    "orange wall banner": "orange_wall_banner",
    "magenta wall banner": "magenta_wall_banner",
    "light blue wall banner": "light_blue_wall_banner",
    "yellow wall banner": "yellow_wall_banner",
    "lime wall banner": "lime_wall_banner",
    "pink wall banner": "pink_wall_banner",
    "gray wall banner": "gray_wall_banner",
    "light gray wall banner": "light_gray_wall_banner",
    "cyan wall banner": "cyan_wall_banner",
    "purple wall banner": "purple_wall_banner",
    "blue wall banner": "blue_wall_banner",
    "brown wall banner": "brown_wall_banner",
    "green wall banner": "green_wall_banner",
    "red wall banner": "red_wall_banner",
    "black wall banner": "black_wall_banner",
    "beetroots": "beetroots",
    "end gateway": "end_gateway",
    "frosted ice": "frosted_ice",
    "kelp plant": "kelp_plant",
    "dead tube coral wall fan": "dead_tube_coral_wall_fan",
    "dead brain coral wall fan": "dead_brain_coral_wall_fan",
    "dead bubble coral wall fan": "dead_bubble_coral_wall_fan",
    "dead fire coral wall fan": "dead_fire_coral_wall_fan",
    "dead horn coral wall fan": "dead_horn_coral_wall_fan",
    "tube coral wall fan": "tube_coral_wall_fan",
    "brain coral wall fan": "brain_coral_wall_fan",
    "bubble coral wall fan": "bubble_coral_wall_fan",
    "fire coral wall fan": "fire_coral_wall_fan",
    "horn coral wall fan": "horn_coral_wall_fan",
    "creeper spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"creeper"}}}',
    "skeleton spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"skeleton"}}}',
    "spider spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"spider"}}}',
    "giant spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"giant"}}}',
    "zombie spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"zombie"}}}',
    "slime spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"slime"}}}',
    "ghast spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"ghast"}}}',
    "pig zombie spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"zombie_pigman"}}}',
    "enderman spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"enderman"}}}',
    "cave spider spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"cave_spider"}}}',
    "silverfish spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"silverfish"}}}',
    "blaze spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"blaze"}}}',
    "magma cube spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"magma_cube"}}}',
    "ender dragon spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"ender_dragon"}}}',
    "wither spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"wither"}}}',
    "bat spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"bat"}}}',
    "witch spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"witch"}}}',
    "pig spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"pig"}}}',
    "sheep spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"sheep"}}}',
    "cow spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"cow"}}}',
    "chicken spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"chicken"}}}',
    "squid spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"squid"}}}',
    "wolf spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"wolf"}}}',
    "mooshroom spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"mooshroom"}}}',
    "snowman spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"snow_golem"}}}',
    "ocelot spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"ocelot"}}}',
    "iron golem spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"iron_golem"}}}',
    "horse spawner": 'spawner{BlockEntityTag:{SpawnData:{id:"horse"}}}',
    "cornflower": "cornflower",
    "lily of the valley": "lily_of_the_valley",
    "wither rose": "wither_rose",
    "smooth stone slab": "smooth_stone_slab",
    "cut sandstone slab": "cut_sandstone_slab",
    "cut red sandstone slab": "cut_red_sandstone_slab",
    "brick wall": "brick_wall",
    "prismarine wall": "prismarine_wall",
    "red sandstone wall": "red_sandstone_wall",
    "mossy stone brick wall": "mossy_stone_brick_wall",
    "granite wall": "granite_wall",
    "stone brick wall": "stone_brick_wall",
    "nether brick wall": "nether_brick_wall",
    "andesite wall": "andesite_wall",
    "red nether brick wall": "red_nether_brick_wall",
    "sandstone wall": "sandstone_wall",
    "end stone brick wall": "end_stone_brick_wall",
    "diorite wall": "diorite_wall",
    "polished granite stairs": "polished_granite_stairs",
    "smooth red sandstone stairs": "smooth_red_sandstone_stairs",
    "mossy stone brick stairs": "mossy_stone_brick_stairs",
    "polished diorite stairs": "polished_diorite_stairs",
    "mossy cobblestone stairs": "mossy_cobblestone_stairs",
    "end stone brick stairs": "end_stone_brick_stairs",
    "stone stairs": "stone_stairs",
    "smooth sandstone stairs": "smooth_sandstone_stairs",
    "smooth quartz stairs": "smooth_quartz_stairs",
    "granite stairs": "granite_stairs",
    "andesite stairs": "andesite_stairs",
    "red nether brick stairs": "red_nether_brick_stairs",
    "polished andesite stairs": "polished_andesite_stairs",
    "diorite stairs": "diorite_stairs",
    "polished granite slab": "polished_granite_slab",
    "smooth red sandstone slab": "smooth_red_sandstone_slab",
    "mossy stone brick slab": "mossy_stone_brick_slab",
    "polished diorite slab": "polished_diorite_slab",
    "mossy cobblestone slab": "mossy_cobblestone_slab",
    "end stone brick slab": "end_stone_brick_slab",
    "smooth sandstone slab": "smooth_sandstone_slab",
    "smooth quartz slab": "smooth_quartz_slab",
    "granite slab": "granite_slab",
    "andesite slab": "andesite_slab",
    "red nether brick slab": "red_nether_brick_slab",
    "polished andesite slab": "polished_andesite_slab",
    "diorite slab": "diorite_slab",
    "scaffolding": "scaffolding",
    "jigsaw block": "jigsaw",
    "composter": "composter",
    "oak sign": "oak_sign",
    "spruce sign": "spruce_sign",
    "birch sign": "birch_sign",
    "jungle sign": "jungle_sign",
    "acacia sign": "acacia_sign",
    "dark oak sign": "dark_oak_sign",
    "bamboo": "bamboo",
    "red dye": "red_dye",
    "green dye": "green_dye",
    "yellow dye": "yellow_dye",
    "blue dye": "blue_dye",
    "brown dye": "brown_dye",
    "black dye": "black_dye",
    "white dye": "white_dye",
    "cat spawn egg": "cat_spawn_egg",
    "fox spawn egg": "fox_spawn_egg",
    "panda spawn egg": "panda_spawn_egg",
    "pillager spawn egg": "pillager_spawn_egg",
    "ravager spawn egg": "ravager_spawn_egg",
    "trader llama spawn egg": "trader_llama_spawn_egg",
    "wandering trader spawn egg": "wandering_trader_spawn_egg",
    "leather horse armor": "leather_horse_armor",
    "crossbow": "crossbow",
    "suspicious stew": "suspicious_stew",
    "loom": "loom",
    "banner pattern": "piglin_banner_pattern",
    "barrel": "barrel",
    "smoker": "smoker",
    "blast furnace": "blast_furnace",
    "cartography table": "cartography_table",
    "fletching table": "fletching_table",
    "grindstone": "grindstone",
    "lectern": "lectern",
    "smithing table": "smithing_table",
    "stonecutter": "stonecutter",
    "bell": "bell",
    "lantern": "lantern",
    "sweet berries": "sweet_berries",
    "campfire": "campfire",
    "bee spawn egg": "bee_spawn_egg",
    "honeycomb": "honeycomb",
    "bee nest": "bee_nest",
    "beehive": "beehive",
    "honey bottle": "honey_bottle",
    "honey block": "honey_block",
    "honeycomb block": "honeycomb_block",
    "oak wall sign": "oak_wall_sign",
    "spruce wall sign": "spruce_wall_sign",
    "birch wall sign": "birch_wall_sign",
    "acacia wall sign": "acacia_wall_sign",
    "jungle wall sign": "jungle_wall_sign",
    "dark oak wall sign": "dark_oak_wall_sign",
    "potted cornflower": "potted_cornflower",
    "potted lily of the valley": "potted_lily_of_the_valley",
    "potted wither rose": "potted_wither_rose",
    "bamboo sapling": "bamboo_sapling",
    "potted bamboo": "potted_bamboo",
    "sweet berry bush": "sweet_berry_bush",
    "crimson nylium": "crimson_nylium",
    "warped nylium": "warped_nylium",
    "crimson planks": "crimson_planks",
    "warped planks": "warped_planks",
    "nether gold ore": "nether_gold_ore",
    "crimson stem": "crimson_stem",
    "warped stem": "warped_stem",
    "stripped crimson stem": "stripped_crimson_stem",
    "stripped warped stem": "stripped_warped_stem",
    "stripped crimson hyphae": "stripped_crimson_hyphae",
    "stripped warped hyphae": "stripped_warped_hyphae",
    "crimson hyphae": "crimson_hyphae",
    "warped hyphae": "warped_hyphae",
    "crimson fungus": "crimson_fungus",
    "warped fungus": "warped_fungus",
    "crimson roots": "crimson_roots",
    "warped roots": "warped_roots",
    "nether sprouts": "nether_sprouts",
    "weeping vines": "weeping_vines",
    "twisting vines": "twisting_vines",
    "crimson slab": "crimson_slab",
    "warped slab": "warped_slab",
    "crimson pressure plate": "crimson_pressure_plate",
    "warped pressure plate": "warped_pressure_plate",
    "polished blackstone pressure plate": "polished_blackstone_pressure_plate",
    "crimson fence": "crimson_fence",
    "warped fence": "warped_fence",
    "soul soil": "soul_soil",
    "basalt": "basalt",
    "polished basalt": "polished_basalt",
    "soul torch": "soul_torch",
    "crimson trapdoor": "crimson_trapdoor",
    "warped trapdoor": "warped_trapdoor",
    "chain": "chain",
    "crimson fence gate": "crimson_fence_gate",
    "warped fence gate": "warped_fence_gate",
    "cracked nether bricks": "cracked_nether_bricks",
    "chiseled nether bricks": "chiseled_nether_bricks",
    "crimson stairs": "crimson_stairs",
    "warped stairs": "warped_stairs",
    "blackstone wall": "blackstone_wall",
    "polished blackstone wall": "polished_blackstone_wall",
    "polished blackstone brick wall": "polished_blackstone_brick_wall",
    "crimson button": "crimson_button",
    "warped button": "warped_button",
    "polished blackstone button": "polished_blackstone_button",
    "quartz bricks": "quartz_bricks",
    "warped wart block": "warped_wart_block",
    "crimson door": "crimson_door",
    "warped door": "warped_door",
    "netherite ingot": "netherite_ingot",
    "netherite scrap": "netherite_scrap",
    "netherite sword": "netherite_sword",
    "netherite shovel": "netherite_shovel",
    "netherite pickaxe": "netherite_pickaxe",
    "netherite axe": "netherite_axe",
    "netherite hoe": "netherite_hoe",
    "netherite helmet": "netherite_helmet",
    "netherite chestplate": "netherite_chestplate",
    "netherite leggings": "netherite_leggings",
    "netherite boots": "netherite_boots",
    "crimson sign": "crimson_sign",
    "warped sign": "warped_sign",
    "hoglin spawn egg": "hoglin_spawn_egg",
    "piglin spawn egg": "piglin_spawn_egg",
    "strider spawn egg": "strider_spawn_egg",
    "zoglin spawn egg": "zoglin_spawn_egg",
    "zombified piglin spawn egg": "zombified_piglin_spawn_egg",
    "warped fungus on a stick": "warped_fungus_on_a_stick",
    "music disc": "music_disc_pigstep",
    "soul lantern": "soul_lantern",
    "soul campfire": "soul_campfire",
    "shroomlight": "shroomlight",
    "lodestone": "lodestone",
    "block of netherite": "netherite_block",
    "ancient debris": "ancient_debris",
    "target": "target",
    "crying obsidian": "crying_obsidian",
    "blackstone": "blackstone",
    "blackstone slab": "blackstone_slab",
    "blackstone stairs": "blackstone_stairs",
    "gilded blackstone": "gilded_blackstone",
    "polished blackstone": "polished_blackstone",
    "polished blackstone slab": "polished_blackstone_slab",
    "polished blackstone stairs": "polished_blackstone_stairs",
    "chiseled polished blackstone": "chiseled_polished_blackstone",
    "polished blackstone bricks": "polished_blackstone_bricks",
    "polished blackstone brick slab": "polished_blackstone_brick_slab",
    "polished blackstone brick stairs": "polished_blackstone_brick_stairs",
    "cracked polished blackstone bricks": "cracked_polished_blackstone_bricks",
    "respawn anchor": "respawn_anchor",
    "soul fire": "soul_fire",
    "soul wall torch": "soul_wall_torch",
    "weeping vines plant": "weeping_vines_plant",
    "twisting vines plant": "twisting_vines_plant",
    "crimson wall sign": "crimson_wall_sign",
    "warped wall sign": "warped_wall_sign",
    "potted crimson fungus": "potted_crimson_fungus",
    "potted warped fungus": "potted_warped_fungus",
    "potted crimson roots": "potted_crimson_roots",
    "potted warped roots": "potted_warped_roots",
    "block of amethyst": "amethyst_block",
    "amethyst bud": "amethyst_bud",
    "amethyst cluster": "amethyst_cluster",
    "amethyst shard": "amethyst_shard",
    "bucket of axolotl": "axolotl_bucket",
    "axolotl spawn egg": "axolotl_spawn_egg",
    "azalea": "azalea",
    "azalea leaves": "azalea_leaves",
    "big dripleaf": "big_dripleaf",
    "black candle": "black_candle",
    "blue candle": "blue_candle",
    "broken elytra": "broken_elytra",
    "brown candle": "brown_candle",
    "budding amethyst": "budding_amethyst",
    "bundle": "bundle",
    "filled bundle": "bundle_filled",
    "calcite": "calcite",
    "candle": "candle",
    "chiseled deepslate": "chiseled_deepslate",
    "cobbled deepslate": "cobbled_deepslate",
    "cobbled deepslate slab": "cobbled_deepslate_slab",
    "cobbled deepslate stairs": "cobbled_deepslate_stairs",
    "cobbled deepslate wall": "cobbled_deepslate_wall",
    "block of copper": "copper_block",
    "copper ingot": "copper_ingot",
    "copper ore": "copper_ore",
    "cracked deepslate bricks": "cracked_deepslate_bricks",
    "cracked deepslate tiles": "cracked_deepslate_tiles",
    "arrow loaded crossbow": "crossbow_arrow",
    "firework loaded crossbow": "crossbow_firework",
    "cut copper": "cut_copper",
    "cut copper slab": "cut_copper_slab",
    "cut copper stairs": "cut_copper_stairs",
    "cyan candle": "cyan_candle",
    "deepslate": "deepslate",
    "deepslate bricks": "deepslate_bricks",
    "deepslate brick slab": "deepslate_brick_slab",
    "deepslate brick stairs": "deepslate_brick_stairs",
    "deepslate brick wall": "deepslate_brick_wall",
    "deepslate coal ore": "deepslate_coal_ore",
    "deepslate copper ore": "deepslate_copper_ore",
    "deepslate diamond ore": "deepslate_diamond_ore",
    "deepslate emerald ore": "deepslate_emerald_ore",
    "deepslate gold ore": "deepslate_gold_ore",
    "deepslate iron ore": "deepslate_iron_ore",
    "deepslate lapis lazuli ore": "deepslate_lapis_ore",
    "deepslate redstone ore": "deepslate_redstone_ore",
    "deepslate tiles": "deepslate_tiles",
    "deepslate tile slab": "deepslate_tile_slab",
    "deepslate tile stairs": "deepslate_tile_stairs",
    "deepslate tile wall": "deepslate_tile_wall",
    "dirt path": "dirt_path",
    "dripstone block": "dripstone_block",
    "exposed copper": "exposed_copper",
    "exposed cut copper": "exposed_cut_copper",
    "exposed cut copper slab": "exposed_cut_copper_slab",
    "exposed cut copper stairs": "exposed_cut_copper_stairs",
    "flowering azalea": "flowering_azalea",
    "flowering azalea leaves": "flowering_azalea_leaves",
    "glow berries": "glow_berries",
    "glow ink sac": "glow_ink_sac",
    "glow item frame": "glow_item_frame",
    "glow lichen": "glow_lichen",
    "glow squid spawn egg": "glow_squid_spawn_egg",
    "goat spawn egg": "goat_spawn_egg",
    "gray candle": "gray_candle",
    "green candle": "green_candle",
    "hanging roots": "hanging_roots",
    "infested deepslate": "infested_deepslate",
    "large amethyst bud": "large_amethyst_bud",
    "lightning rod": "lightning_rod",
    "light blue candle": "light_blue_candle",
    "light gray candle": "light_gray_candle",
    "lime candle": "lime_candle",
    "magenta candle": "magenta_candle",
    "medium amethyst bud": "medium_amethyst_bud",
    "moss block": "moss_block",
    "moss carpet": "moss_carpet",
    "orange candle": "orange_candle",
    "oxidized copper": "oxidized_copper",
    "oxidized cut copper": "oxidized_cut_copper",
    "oxidized cut copper slab": "oxidized_cut_copper_slab",
    "oxidized cut copper stairs": "oxidized_cut_copper_stairs",
    "piglin brute spawn egg": "piglin_brute_spawn_egg",
    "pink candle": "pink_candle",
    "pointed dripstone": "pointed_dripstone",
    "polished deepslate": "polished_deepslate",
    "polished deepslate slab": "polished_deepslate_slab",
    "polished deepslate stairs": "polished_deepslate_stairs",
    "polished deepslate wall": "polished_deepslate_wall",
    "powder snow bucket": "powder_snow_bucket",
    "purple candle": "purple_candle",
    "raw copper": "raw_copper",
    "block of raw copper": "raw_copper_block",
    "raw gold": "raw_gold",
    "block of raw gold": "raw_gold_block",
    "raw iron": "raw_iron",
    "block of raw iron": "raw_iron_block",
    "red candle": "red_candle",
    "rooted dirt": "rooted_dirt",
    "sculk sensor": "sculk_sensor",
    "small amethyst bud": "small_amethyst_bud",
    "small dripleaf": "small_dripleaf",
    "smooth basalt": "smooth_basalt",
    "spore blossom": "spore_blossom",
    "spyglass": "spyglass",
    "tinted glass": "tinted_glass",
    "tuff": "tuff",
    "waxed block of copper": "waxed_copper_block",
    "waxed cut copper": "waxed_cut_copper",
    "waxed cut copper slab": "waxed_cut_copper_slab",
    "waxed cut copper stairs": "waxed_cut_copper_stairs",
    "waxed exposed copper": "waxed_exposed_copper",
    "waxed exposed cut copper": "waxed_exposed_cut_copper",
    "waxed exposed cut copper slab": "waxed_exposed_cut_copper_slab",
    "waxed exposed cut copper stairs": "waxed_exposed_cut_copper_stairs",
    "waxed oxidized copper": "waxed_oxidized_copper",
    "waxed oxidized cut copper": "waxed_oxidized_cut_copper",
    "waxed oxidized cut copper slab": "waxed_oxidized_cut_copper_slab",
    "waxed oxidized cut copper stairs": "waxed_oxidized_cut_copper_stairs",
    "waxed weathered copper": "waxed_weathered_copper",
    "waxed weathered cut copper": "waxed_weathered_cut_copper",
    "waxed weathered cut copper slab": "waxed_weathered_cut_copper_slab",
    "waxed weathered cut copper stairs": "waxed_weathered_cut_copper_stairs",
    "weathered copper": "weathered_copper",
    "weathered cut copper": "weathered_cut_copper",
    "weathered cut copper slab": "weathered_cut_copper_slab",
    "weathered cut copper stairs": "weathered_cut_copper_stairs",
    "white candle": "white_candle",
    "yellow candle": "yellow_candle",
    "otherside disc": "music_disc_otherside",
}
