Mobs = {
    "axolotl": "axolotl",
    "bat": "bat",
    "bee": "bee",
    "blaze": "blaze",
    "camel": "camel",
    "cat": "cat",
    "cave spider": "cave_spider",
    "chicken": "chicken",
    "cod": "cod",
    "cow": "cow",
    "creeper": "creeper",
    "dolphin": "dolphin",
    "donkey": "donkey",
    "drowned": "drowned",
    "elder guardian": "elder_guardian",
    "ender dragon": "ender_dragon",
    "enderman": "enderman",
    "endermite": "endermite",
    "evoker": "evoker",
    "fox": "fox",
    "ghast": "ghast",
    "giant": "giant",
    "glow squid": "glow_squid",
    "goat": "goat",
    "guardian": "guardian",
    "hoglin": "hoglin",
    "horse": "horse",
    "husk": "husk",
    "illusioner": "illusioner",
    "iron golem": "iron_golem",
    "llama": "llama",
    "magma cube": "magma_cube",
    "mooshroom": "mooshroom",
    "mule": "mule",
    "ocelot": "ocelot",
    "panda": "panda",
    "parrot": "parrot",
    "phantom": "phantom",
    "pig": "pig",
    "piglin": "piglin",
    "piglin brute": "piglin_brute",
    "pillager": "pillager",
    "polar bear": "polar_bear",
    "pufferfish": "pufferfish",
    "rabbit": "rabbit",
    "ravager": "ravager",
    "salmon": "salmon",
    "sheep": "sheep",
    "shulker": "shulker",
    "silverfish": "silverfish",
    "sniffer": "sniffer",
    "skeleton": "skeleton",
    "skeleton horse": "skeleton_horse",
    "slime": "slime",
    "snow golem": "snow_golem",
    "spider": "spider",
    "squid": "squid",
    "stray": "stray",
    "strider": "strider",
    "trader llama": "trader_llama",
    "tropical fish": "tropical_fish",
    "turtle": "turtle",
    "vex": "vex",
    "villager": "villager",
    "vindicator": "vindicator",
    "wandering trader": "wandering_trader",
    "witch": "witch",
    "wither": "wither",
    "wither skeleton": "wither_skeleton",
    "wolf": "wolf",
    "zoglin": "zoglin",
    "zombie": "zombie",
    "zombie horse": "zombie_horse",
    "zombie villager": "zombie_villager",
    "zombified piglin": "zombified_piglin",
    "allay": "allay",
    "frog": "frog",
    "tadpole": "tadpole",
    "warden": "warden",
}
